package adapter

import "strings"

type teachingCatalogItem struct {
	name        string
	section     string
	label       string
	method      string
	path        string
	description string
	mutating    bool
	fields      []string
}

var teachingRoutes = []teachingCatalogItem{
	{"home", "全局", "首页", "GET", "/meol/index.do?menuId=1", "个人首页、通知、日历、课程列表", false, []string{}},
	{"learning", "全局", "学习", "GET", "/meol/custom.do?menuId=2", "课程排行与荣誉级别", false, []string{}},
	{"activities", "全局", "活动", "GET", "/meol/custom.do?menuId=3", "研究型教学活动查询", false, []string{}},
	{"activity-search", "活动", "研究型教学查询", "GET", "/meol/activity.do?menuId=3", "按范围和主题查询研究型教学", false, []string{}},
	{"activity-course-list", "活动", "研究型教学课程列表", "GET", "/meol/homepage/V8/include/issue_course_list.jsp", "研究型教学课程列表 iframe", false, []string{}},
	{"podcast", "全局", "播客", "GET", "/meol/custom.do?menuId=4", "微课/播客检索、播放、评论与分页", false, []string{}},
	{"excellent-courses", "全局", "精品课", "GET", "/meol/custom.do?menuId=5", "精品课程申报和国家、省、校级课程", false, []string{}},
	{"resource-center", "全局", "资源中心", "GET", "/meol/respush/res/res_sso.jsp?resourceIndex=1", "公共资源、资源库、个人资源空间", false, []string{}},
	{"resource-sso", "资源中心", "资源中心 SSO 交接", "GET", "/moocresource/eol_sso_new.jsp", "从教学平台进入资源中心的 SSO 交接页", false, []string{}},
	{"course-union", "全局", "课程联盟", "GET", "/meol/courseunion/index.jsp?menuId=8", "课程联盟", false, []string{}},
	{"personal", "全局", "个人", "GET", "/meol/personal.do?menuId=0", "个人资料、提醒、通知、日历和课程", false, []string{}},
	{"social", "全局", "学习社区", "GET", "/meol/social/socialIndex.do?menuId=9", "学习社区", false, []string{}},
	{"social-friend-search", "学习社区", "找人", "GET", "/meol/social/friendSearch.do", "按姓名、性别、学校、年份、班级、专业找人", false, []string{}},
	{"social-course-search", "学习社区", "找课程", "GET", "/meol/social/coursesSearch.do", "社区课程搜索 iframe", false, []string{}},
	{"social-circle-search", "学习社区", "找圈子", "GET", "/meol/social/studyCircleSearch.do", "学习圈搜索", false, []string{}},
	{"social-circle", "学习社区", "学习圈详情", "GET", "/meol/social/studyCircleInfo.do", "学习圈详情和成员动态", false, []string{}},
	{"social-circle-list", "学习社区", "我的圈子", "GET", "/meol/social/studyCircleList.do", "我的学习圈列表", false, []string{}},
	{"social-person", "学习社区", "个人社区主页", "GET", "/meol/social/viewPersonInfo.do", "社区个人信息和动态", false, []string{}},
	{"social-news", "学习社区", "社区动态", "GET", "/meol/social/listNews.do", "个人或圈子动态", false, []string{}},
	{"social-topics", "学习社区", "我的话题", "GET", "/meol/social/listTopics.do", "个人话题列表", false, []string{}},
	{"social-attention", "学习社区", "关注列表", "GET", "/meol/social/listAttention.do", "关注的人和圈子", false, []string{}},
	{"social-fans", "学习社区", "粉丝列表", "GET", "/meol/social/listMyFans.do", "我的粉丝", false, []string{}},
	{"social-new-circle", "学习社区", "创建圈子", "GET", "/meol/social/preAddStudyCircle.do", "创建学习圈表单", false, []string{}},
	{"social-edit-person", "学习社区", "编辑社区资料", "GET", "/meol/social/preUpdPersonInfo.do", "编辑社区个人资料", false, []string{}},
	{"social-upload-image", "学习社区", "上传社区图片", "GET", "/meol/lifelong/social/uploadimg.jsp", "社区图片上传 iframe", false, []string{}},
	{"social-date-picker", "学习社区", "社区日期选择器", "GET", "/meol/lifelong/social/My97DatePicker.htm", "社区日期选择器 iframe", false, []string{}},
	{"social-download-file", "学习社区", "下载社区文件", "GET", "/meol/downloadTheolFile.do", "下载社区图片/文件", false, []string{}},
	{"course-jump", "学习社区", "进入社区课程", "GET", "/meol/lesson/mainJumpPage.jsp", "从社区进入课程", false, []string{}},
	{"department", "全局", "虚拟教研室", "GET", "/meol/department.do?deptId=78401", "虚拟教研室", false, []string{}},
	{"course-search", "全局", "课程搜索", "GET", "/meol/course.do", "按课程名称/编号查询课程", false, []string{}},
	{"course-departments", "全局", "课程院系列表", "GET", "/meol/allDepartment.do", "课程搜索的院系筛选列表", false, []string{}},
	{"course-curriculum", "全局", "培养方案课程表", "GET", "/meol/homepage/V8/include/course_curriculum.jsp", "院系培养方案及课程表", false, []string{}},
	{"password-recovery", "全局", "找回密码", "GET", "/meol/findPasswdIndex.do", "登录页找回密码入口", false, []string{}},
	{"password-email-pre", "全局", "邮箱找回密码", "GET", "/meol/findPasswdMailBoxPreAccount.do", "通过邮箱验证身份", false, []string{}},
	{"password-email-receive", "全局", "接收重置邮件", "GET", "/meol/findPasswdMailBoxReceive.do", "邮箱找回密码结果页", false, []string{}},
	{"password-question-pre", "全局", "提示问题找回密码", "GET", "/meol/findPasswdQuestionPreAccount.do", "通过提示问题验证身份", false, []string{}},
	{"password-question-reset", "全局", "重置密码", "GET", "/meol/findPasswdQuestionPreReset.do", "提示问题验证后的密码重置页", false, []string{}},
	{"password-captcha", "全局", "找回密码验证码", "GET", "/meol/getCaptcha.do", "获取找回密码验证码图片", false, []string{}},
	{"platform-login", "全局", "旧版登录表单", "GET", "/meol/loginCheck.do", "未通过统一认证时的平台登录表单", false, []string{}},
	{"learning-menu", "学习管理", "学习管理菜单", "GET", "/meol/left_v8.jsp", "学习管理隐藏菜单 iframe", false, []string{}},
	{"research-menu", "研究型教学", "研究型教学菜单", "GET", "/meol/issueteach/left.jsp", "研究型教学隐藏菜单 iframe", false, []string{}},
	{"excellent-menu", "精品课", "精品课程菜单", "GET", "/meol/jpk/student/left.jsp", "精品课程隐藏菜单 iframe", false, []string{}},
	{"podcast-menu", "播客", "教学播客菜单", "GET", "/meol/common/vblog/stu_left.jsp", "教学播客隐藏菜单 iframe", false, []string{}},
	{"podcast-inner", "播客", "教学播客首页", "GET", "/meol/common/vblog/inner_index.jsp", "教学播客隐藏首页", false, []string{}},
	{"consultation-menu", "公共组件", "应用咨询菜单", "GET", "/meol/popups/teach_v8/student_popups.jsp", "应用咨询隐藏菜单 iframe", false, []string{}},
	{"consultation", "公共组件", "应用咨询", "GET", "/meol/popups/student_1.htm", "应用咨询内容", false, []string{}},
	{"department-teachers", "虚拟教研室", "教研室教师", "GET", "/meol/teacher.do", "按教研室查看教师", false, []string{}},
	{"honor-courses", "虚拟教研室", "荣誉课程", "GET", "/meol/honLesson.do", "荣誉课程列表", false, []string{}},
	{"honor-teachers", "虚拟教研室", "荣誉教师", "GET", "/meol/honTeacher.do", "荣誉教师列表", false, []string{}},
	{"global-logout", "全局", "平台退出", "GET", "/meol/homepage/V8/include/logout.jsp", "退出教学平台", false, []string{}},
	{"student-info", "个人", "学生信息", "GET", "/meol/popups/viewstudent_info.jsp", "查看和编辑个人资料", false, []string{}},
	{"student-info-edit", "个人", "编辑学生信息", "GET", "/meol/popups/student_info_modify.jsp", "编辑邮箱和电话", false, []string{}},
	{"security", "个人", "安全设置", "GET", "/meol/lifelong/user/security_info.jsp", "修改密码和安全问答", false, []string{}},
	{"password", "个人", "修改密码", "GET", "/meol/popups/password.jsp", "修改密码弹窗", false, []string{}},
	{"password-update", "个人", "提交新密码", "GET", "/meol/popups/password_do.jsp", "提交密码修改", false, []string{}},
	{"security-question", "个人", "安全问题验证", "GET", "/meol/validateQuestion.do", "设置安全问题页面", false, []string{}},
	{"security-question-update", "个人", "提交安全问题", "GET", "/meol/validateQuestionDo.do", "提交安全问题答案", false, []string{}},
	{"security-email-verify", "个人", "验证邮箱", "GET", "/meol/validateEmailSend.do", "发送邮箱验证", false, []string{}},
	{"security-mobile", "个人", "绑定手机", "GET", "/meol/lifelong/user/bind_mobile.jsp", "绑定或更换手机", false, []string{}},
	{"bind-mobile-reminder", "个人", "绑定手机提醒", "GET", "/meol/lifelong/user/bind_mobile_ignore.jsp", "绑定手机提醒弹窗", false, []string{}},
	{"mobile-login", "个人", "手机验证码登录", "GET", "/meol/mobileLogin.do", "使用手机验证码登录教学平台", false, []string{}},
	{"bind-mobile-ignore", "个人", "暂不绑定手机", "GET", "/meol/bindMobileIgnore.do", "关闭绑定手机提醒", false, []string{}},
	{"notifications", "个人", "系统通知", "GET", "/meol/common/inform/index_stu.jsp", "通知排序、分页和详情", false, []string{}},
	{"notification", "个人", "通知详情", "GET", "/meol/common/inform/message_content.jsp", "查看单条通知", false, []string{}},
	{"home-notifications-all", "全局", "全部通知", "GET", "/meol/homepage/common/inform_all.jsp", "首页查看更多系统通知", false, []string{}},
	{"calendar", "个人", "日历", "GET", "/meol/common/calendar/index.jsp", "日历入口", false, []string{}},
	{"calendar-month", "个人", "月日历", "GET", "/meol/common/calendar/month.jsp", "按月查看日历", false, []string{}},
	{"calendar-date", "个人", "日日历", "GET", "/meol/common/calendar/date.jsp", "按日查看日历", false, []string{}},
	{"all-courses", "个人", "全部课程", "GET", "/meol/lesson/blen.student.lesson.list.jsp", "课程搜索和课程顺序调整", false, []string{}},
	{"course-apply", "学习管理", "申请课程", "GET", "/meol/lesson/applynewcourse_stu.jsp", "检索可申请课程", false, []string{}},
	{"course-summary", "学习管理", "课程简介", "GET", "/meol/lesson/coursesum.jsp", "查看可申请课程简介", false, []string{}},
	{"course-join", "学习管理", "加入课程", "GET", "/meol/lesson/applyjoincourse.jsp", "申请加入课程", false, []string{}},
	{"course-archive", "学习管理", "历史课程", "GET", "/meol/archive/archiveCourseListByStu.do", "查看历史课程", false, []string{}},
	{"mail", "站内邮箱", "邮箱首页", "GET", "/meol/common/mail/index.jsp", "站内邮箱入口", false, []string{}},
	{"mail-inbox", "站内邮箱", "收件箱", "GET", "/meol/common/mail/inputbox.jsp", "收件箱和邮件操作", false, []string{}},
	{"mail-sent", "站内邮箱", "已发送", "GET", "/meol/common/mail/sent.jsp", "已发送邮件", false, []string{}},
	{"mail-draft", "站内邮箱", "草稿箱", "GET", "/meol/common/mail/draft.jsp", "草稿邮件", false, []string{}},
	{"mail-trash", "站内邮箱", "垃圾箱", "GET", "/meol/common/mail/garbage.jsp", "垃圾邮件和清空操作", false, []string{}},
	{"mail-folders", "站内邮箱", "邮箱文件夹", "GET", "/meol/common/mail/managefolder.jsp", "管理邮箱文件夹", false, []string{}},
	{"mail-contacts", "站内邮箱", "邮箱联系人", "GET", "/meol/common/mail/managecontact.jsp", "管理邮箱联系人", false, []string{}},
	{"mail-compose", "站内邮箱", "写邮件", "GET", "/meol/common/mail/composemail.jsp", "写信、发送和保存草稿", false, []string{}},
	{"mail-edit-folder", "站内邮箱", "编辑邮箱文件夹", "GET", "/meol/common/mail/editfolder.jsp", "新建或编辑邮箱文件夹", false, []string{}},
	{"mail-edit-contact", "站内邮箱", "编辑邮箱联系人", "GET", "/meol/common/mail/editcontact.jsp", "新建或编辑邮箱联系人", false, []string{}},
	{"mail-search", "站内邮箱", "搜索邮件", "GET", "/meol/common/mail/search.jsp", "搜索站内邮件", false, []string{}},
	{"mail-message", "站内邮箱", "邮件详情", "GET", "/meol/common/mail/mail.jsp", "查看单封邮件", false, []string{}},
	{"mail-settings", "站内邮箱", "邮箱设置", "GET", "/meol/common/mail/mailsetting.jsp", "邮箱通知设置", false, []string{}},
	{"mail-contact-search", "站内邮箱", "联系人搜索详情", "GET", "/meol/common/mail/search_info.jsp", "搜索并选择联系人", false, []string{}},
	{"daily-top", "学习", "日排行", "GET", "/meol/homepage/common/today_lesson_top_list.jsp", "课程日排行", false, []string{}},
	{"total-top", "学习", "总排行", "GET", "/meol/homepage/common/total_lesson_top_list.jsp", "课程总排行", false, []string{}},
	{"rank", "学习", "荣誉级别", "GET", "/meol/homepage/V8/include/rank_lesson_content.jsp", "荣誉级别内容", false, []string{}},
	{"research-teaching", "活动", "研究型教学", "GET", "/meol/issueteach/issue/myissue/issue_list.jsp?_style=new03", "研究型教学主题", false, []string{}},
	{"research-public", "研究型教学", "校级研究型教学", "GET", "/meol/issueteach/issue/pubissue_list.jsp", "校级研究型教学主题", false, []string{}},
	{"research-course-list", "研究型教学", "课程研究型教学", "GET", "/meol/issueteach/issue/courseissue_list_stu.jsp", "按课程查看研究型教学", false, []string{}},
	{"research-my-all", "研究型教学", "我的研究型教学", "GET", "/meol/issueteach/issue/myissue/my_issue_allcourse.jsp", "跨课程查看我的研究型教学", false, []string{}},
	{"podcast-detail", "播客", "播客详情", "GET", "/meol/common/vblog/videodetail.jsp", "播客详情、属性和评论入口", false, []string{}},
	{"podcast-play", "播客", "播客播放", "GET", "/meol/microlessonunit/podcast.do", "播放播客资源", false, []string{}},
	{"podcast-player", "播客", "播客播放器", "GET", "/meol/common/stream/player.jsp", "播放流媒体播客", false, []string{}},
	{"podcast-recommend", "播客", "播客推荐", "GET", "/meol/common/vblog/recommend.jsp", "推荐播客", false, []string{}},
	{"podcast-favorite", "播客", "播客收藏", "GET", "/meol/common/vblog/favorite/add_favorite.jsp", "收藏播客", false, []string{}},
	{"podcast-review", "播客", "播客评论", "GET", "/meol/common/vblog/reviewvideo.jsp", "查看/发布播客评论", false, []string{}},
	{"podcast-list", "播客", "全校视频", "GET", "/meol/common/vblog/listvideo.jsp", "全校视频列表和筛选", false, []string{}},
	{"podcast-favorites", "播客", "我的播客收藏", "GET", "/meol/common/vblog/favorite/favorite_video.jsp", "查看和删除播客收藏", false, []string{}},
	{"podcast-recent", "播客", "近期点播", "GET", "/meol/common/vblog/recentvideo.jsp", "近期点播视频", false, []string{}},
	{"podcast-favorite-delete", "播客", "删除播客收藏", "GET", "/meol/common/vblog/favorite/del_favorite.jsp", "批量删除播客收藏", false, []string{}},
	{"excellent-current", "精品课", "当前申报", "GET", "/meol/jpkContent.do", "当前精品课申报", false, []string{}},
	{"excellent-history", "精品课", "历次申报", "GET", "/meol/jpkContent.do", "历次精品课申报", false, []string{}},
	{"excellent-national", "精品课", "国家级精品课", "GET", "/meol/jpkContent.do?jpkNewsId=3", "国家级精品课", false, []string{}},
	{"excellent-provincial", "精品课", "省级精品课", "GET", "/meol/jpkContent.do?jpkNewsId=4", "省级精品课", false, []string{}},
	{"excellent-university", "精品课", "校级精品课", "GET", "/meol/jpkContent.do?jpkNewsId=5", "校级精品课", false, []string{}},
	{"excellent-apply", "精品课", "当前精品课程申报", "GET", "/meol/jpk/teacher/ela_sect_apply.jsp", "精品课程申报列表", false, []string{}},
	{"excellent-course-list", "精品课", "历年精品课程", "GET", "/meol/jpk/teacher/ela_sect.jsp", "历年精品课程列表", false, []string{}},
	{"excellent-course-manage", "精品课", "精品课程详情列表", "GET", "/meol/jpk/teacher/coursemanage_byselect.jsp", "按申报期查看课程", false, []string{}},
	{"excellent-course", "精品课", "精品课程浏览", "GET", "/meol/jpk/course/index.jsp", "浏览申报课程", false, []string{}},
	{"resource-home", "资源中心", "资源首页", "GET", "/moocresource/index/index.jsp", "资源搜索、推荐和统计", false, []string{}},
	{"resource-login", "资源中心", "资源中心登录", "GET", "/moocresource/servlet/loginServlet", "资源中心登录表单", false, []string{}},
	{"resource-home-search", "资源中心", "资源首页搜索", "GET", "/moocresource/view/reslist.jsp", "资源首页关键词搜索", false, []string{}},
	{"resource-excellent", "资源中心", "优秀课程", "GET", "/moocresource/courses/excellent/indextop.jsp", "优秀课程资源", false, []string{}},
	{"resource-open", "资源中心", "公开课", "GET", "/moocresource/courses/ocw/ocwindex.jsp", "开放课程资源", false, []string{}},
	{"resource-video", "资源中心", "校友会视频", "GET", "/moocresource/courses/xiaoyouhui/video_intro.jsp", "校友会视频", false, []string{}},
	{"resource-mooc", "资源中心", "校友会 MOOC", "GET", "/moocresource/courses/xiaoyouhui/mooc_intro.jsp", "校友会 MOOC", false, []string{}},
	{"resource-micro", "资源中心", "校友会微课", "GET", "/moocresource/courses/xiaoyouhui/micro_intro.jsp", "校友会微课", false, []string{}},
	{"resource-banks", "资源中心", "资源库", "GET", "/moocresource/banks/banksindex.jsp", "资源库和分类资源检索", false, []string{}},
	{"resource-space", "资源中心", "我的资源", "GET", "/moocresource/myres/spaceindex.jsp", "个人资源、文件夹和批量操作", false, []string{}},
	{"resource-logout", "资源中心", "资源中心退出", "GET", "/moocresource/logout.jsp", "退出资源中心会话", false, []string{}},
	{"resource-left", "资源中心", "资源空间菜单", "GET", "/moocresource/myres/left.jsp", "个人资源菜单 iframe", false, []string{}},
	{"resource-list-frame", "资源中心", "资源列表框架", "GET", "/moocresource/resource/resourceInfoList.do", "资源列表 iframe", false, []string{}},
	{"resource-add", "资源中心", "添加资源", "GET", "/moocresource/resource/preAddResourceInfo.do", "添加资源页面", false, []string{}},
	{"resource-move-batch", "资源中心", "批量移动资源", "GET", "/moocresource/resource/moveResourceInfoByBatch.do", "批量移动资源", false, []string{}},
	{"resource-delete-batch", "资源中心", "批量删除资源", "GET", "/moocresource/resource/deleteResourceInfoByBatch.do", "批量删除资源", false, []string{}},
	{"resource-folders-frame", "资源中心", "资源目录框架", "GET", "/moocresource/resource/listMyFolder.do", "资源目录 iframe", false, []string{}},
	{"resource-favorites-frame", "资源中心", "收藏框架", "GET", "/moocresource/myres/favorite/favorite_detail.jsp", "收藏资源 iframe", false, []string{}},
	{"resource-follows-frame", "资源中心", "关注框架", "GET", "/moocresource/myres/attentionres/attentionres_list.jsp", "关注资源 iframe", false, []string{}},
	{"resource-comments-frame", "资源中心", "评论框架", "GET", "/moocresource/myres/myreview/reviewlist.jsp", "资源评论 iframe", false, []string{}},
	{"resource-shares-frame", "资源中心", "共享资源框架", "GET", "/moocresource/resource/listShareRes.do", "共享资源 iframe", false, []string{}},
	{"resource-personal-frame", "资源中心", "个人信息框架", "GET", "/moocresource/personalset/class_personal_info.jsp", "资源个人信息 iframe", false, []string{}},
	{"resource-view", "资源中心", "共享资源详情", "GET", "/moocresource/resource/viewResourceInfo.do", "共享资源详情", false, []string{}},
	{"resource-favorite", "资源中心", "收藏资源", "GET", "/moocresource/myres/favorite/favorite.jsp", "收藏或取消收藏资源", false, []string{}},
	{"resource-rate", "资源中心", "资源评分", "GET", "/moocresource/search/res_evaluate.jsp", "资源一至五星评分", false, []string{}},
	{"resource-download", "资源中心", "下载资源", "GET", "/moocresource/servlet/ResourceDownload", "下载资源文件", false, []string{}},
	{"resource-tag-exists", "资源中心", "检查资源标签", "GET", "/moocresource/taglibrary/tagExist.do", "检查标签是否存在", false, []string{}},
	{"resource-tag-add", "资源中心", "添加资源标签", "GET", "/moocresource/taglibrary/tagAdd.do", "添加资源标签", false, []string{}},
	{"folder-add", "资源中心", "添加资源目录", "GET", "/moocresource/resource/preAddFolder.do", "添加资源目录页面", false, []string{}},
	{"folder-update", "资源中心", "更新资源目录", "GET", "/moocresource/resource/updateMySelfFolder.do", "更新资源目录", false, []string{}},
	{"folder-share-batch", "资源中心", "批量共享目录", "GET", "/moocresource/resource/shareFolderBatch.do", "共享或取消共享目录", false, []string{}},
	{"folder-list", "资源中心", "收藏夹目录管理", "GET", "/moocresource/resource/myfolder_list.jsp", "管理收藏夹目录", false, []string{}},
	{"follow-add", "资源中心", "添加资源关注", "GET", "/moocresource/myres/attentionres/attentionres_add.jsp", "添加资源关注", false, []string{}},
	{"resource-list", "资源中心", "个人资源列表", "GET", "/moocresource/myres/resourceInfoList.do", "个人资源筛选、排序和分页", false, []string{}},
	{"resource-folders", "资源中心", "资源文件夹", "GET", "/moocresource/myres/listMyFolder.do", "文件夹新建、共享和删除", false, []string{}},
	{"resource-favorites", "资源中心", "资源收藏", "GET", "/moocresource/myres/favorite_detail.jsp", "收藏夹和收藏资源", false, []string{}},
	{"resource-follows", "资源中心", "资源关注", "GET", "/moocresource/myres/attentionres_list.jsp", "关注的资源", false, []string{}},
	{"resource-comments", "资源中心", "资源评论", "GET", "/moocresource/myres/reviewlist.jsp", "资源评论", false, []string{}},
	{"resource-shares", "资源中心", "共享资源", "GET", "/moocresource/myres/listShareRes.do", "共享资源筛选、排序和分页", false, []string{}},
	{"resource-personal", "资源中心", "资源个人信息", "GET", "/moocresource/myres/class_personal_info.jsp", "资源积分、等级和统计", false, []string{}},
	{"resource-notifications", "资源中心", "资源通知", "GET", "/moocresource/common/inform/index_all.jsp", "资源通知", false, []string{}},
	{"resource-updates", "资源中心", "资源最新更新", "GET", "/moocresource/statistics/all_new_list.jsp", "最新资源更新", false, []string{}},
	{"resource-bank-subject", "资源中心", "资源库分类", "GET", "/moocresource/banks/banksindex.jsp", "按学科和类型浏览资源", false, []string{}},
	{"resource-bank-login", "资源中心", "资源库登录提示", "GET", "/moocresource/banks/login.jsp", "资源库登录提示和返回入口", false, []string{}},
	{"resource-bank-subject-list", "资源中心", "资源库分类列表", "GET", "/moocresource/banks/search/bank_index.jsp", "按专题库分类浏览资源", false, []string{}},
	{"resource-bank", "资源中心", "资源库首页", "GET", "/moocresource/banks/search/bank.jsp", "专题库详情首页", false, []string{}},
	{"resource-bank-left", "资源中心", "资源库分类菜单", "GET", "/moocresource/banks/search/left.jsp", "专题库分类菜单 iframe", false, []string{}},
	{"resource-bank-left-submenu", "资源中心", "资源库子分类菜单", "GET", "/moocresource/banks/search/left-submenu.jsp", "专题库子分类菜单", false, []string{}},
	{"resource-bank-list", "资源中心", "资源库资源列表", "GET", "/moocresource/banks/search/reslist.jsp", "专题库资源检索列表", false, []string{}},
	{"resource-excellent-list", "资源中心", "精品课程列表", "GET", "/moocresource/courses/excellent/course_list_query.jsp", "精品课程检索结果", false, []string{}},
	{"resource-open-list", "资源中心", "全球开放课程列表", "GET", "/moocresource/courses/ocw/ocwcoursesearch.jsp", "全球开放课程检索结果", false, []string{}},
	{"resource-video-list", "资源中心", "公开视频列表", "GET", "/moocresource/courses/xiaoyouhui/video_list_query.jsp", "公开视频检索结果", false, []string{}},
	{"resource-mooc-list", "资源中心", "MOOC列表", "GET", "/moocresource/courses/xiaoyouhui/mooc_list_query.jsp", "MOOC检索结果", false, []string{}},
	{"resource-micro-list", "资源中心", "微课程列表", "GET", "/moocresource/courses/xiaoyouhui/micro_list_query.jsp", "微课程检索结果", false, []string{}},
	{"resource-tag-list", "资源中心", "标签资源列表", "GET", "/moocresource/courses/xiaoyouhui/searchresourcebytag.jsp", "按标签检索资源", false, []string{}},
	{"resource-entry-detail", "资源中心", "资源外部条目", "GET", "/moocresource/search/browser_by_entry.jsp", "按外部条目标识查看资源", false, []string{}},
	{"resource-search", "资源中心", "资源检索", "GET", "/moocresource/search/browser.jsp", "资源详情和检索结果", false, []string{}},
	{"resource-detail", "资源中心", "资源详情", "GET", "/moocresource/search/browser.jsp", "预览、属性、收藏、下载、评论和标签", false, []string{}},
	{"resource-attribute", "资源中心", "资源属性", "GET", "/moocresource/banks/search/attribute.jsp", "资源属性", false, []string{}},
	{"resource-related", "资源中心", "相关资源", "GET", "/moocresource/banks/relateres.jsp", "相关资源", false, []string{}},
	{"course", "课程", "课程首页", "GET", "/meol/jpk/course/layout/newpage/index.jsp", "课程壳和所有课程菜单", false, []string{}},
	{"course-default", "课程", "课程介绍首页", "GET", "/meol/jpk/course/layout/newpage/default_demonstrate.jsp", "课程介绍和最新动态 iframe", false, []string{}},
	{"course-unit-blank", "课程", "单元学习容器", "GET", "/meol/jpk/course/layout/_blank.jsp", "单元学习容器页面", false, []string{}},
	{"course-qrcode", "课程", "课程二维码", "GET", "/meol/lesson/qrcode.jsp", "显示课程二维码", false, []string{}},
	{"course-logout", "全局", "教学平台退出", "GET", "/meol/homepage/common/logout.jsp", "退出网络教学平台", false, []string{}},
	{"course-user-stat", "课程", "课程统计", "GET", "/meol/jpk/course/userLessonStat.jsp", "课程首页统计数据", false, []string{}},
	{"course-online-heartbeat", "课程", "在线时长心跳", "GET", "/meol/lesson/onlinetime_listener.jsp", "记录课程在线时长", false, []string{}},
	{"online-help", "公共组件", "在线帮助", "GET", "/meol/common/help/help.jsp", "当前页面在线帮助", false, []string{}},
	{"public-course", "课程", "公开课程首页", "GET", "/meol/homepage/course/course_index.jsp", "排行和公开课程入口", false, []string{}},
	{"course-lesson-home", "课程", "课程学习首页", "GET", "/meol/jpk/course/layout/lesson/index.jsp", "课程学习首页", false, []string{}},
	{"course-column", "课程", "课程栏目", "GET", "/meol/jpk/course/course_column_preview_transfer.jsp?tagbug=client", "课程学习/基本信息/课程活动栏目", false, []string{}},
	{"course-notices", "课程", "课程通知", "GET", "/meol/article/ListNews.do", "课程通知列表", false, []string{}},
	{"course-notice", "课程", "课程通知详情", "GET", "/meol/jpk/course/layout/course_meswrap.jsp", "课程通知详情", false, []string{}},
	{"course-resources", "课程", "课程资源", "GET", "/meol/common/script/courseResource.jsp", "课程资源框架和文件夹", false, []string{}},
	{"course-resource-list", "课程", "课程资源列表", "GET", "/meol/common/script/listview.jsp", "课程资源列表、目录属性和分页", false, []string{}},
	{"course-resource-search", "课程", "课程资源搜索", "GET", "/meol/common/script/search.jsp", "课程资源搜索条件", false, []string{}},
	{"course-resource-preview", "课程", "课程资源预览", "GET", "/meol/common/script/preview/download_preview.jsp", "课程资源预览/下载", false, []string{}},
	{"course-micro-lessons", "课程", "教学播课", "GET", "/meol/microlessonunit/viewMicroLesson.do", "播课单元和视频", false, []string{}},
	{"course-analytics", "课程", "学习分析", "GET", "/meol/jpk/course/blended_module/mod_la_stu.jsp", "学习时长、进入次数和课程行为", false, []string{}},
	{"course-analytics-info", "课程", "学习分析信息", "GET", "/meol/la/student/course_info.jsp", "学习分析统计信息", false, []string{}},
	{"course-analytics-chart", "课程", "学习分析图表", "GET", "/meol/la/student/script_view.jsp", "学习分析图表", false, []string{}},
	{"course-analytics-enter", "课程", "课程进入记录", "GET", "/meol/la/student/lesson_enter.jsp", "课程进入次数和学习时间", false, []string{}},
	{"course-score", "课程", "课程成绩", "GET", "/meol/newscoremanagement/scoreView.do", "课程成绩详情", false, []string{}},
	{"course-score-view", "课程", "课程成绩单", "GET", "/meol/scoremanagement/scoreView.do", "课程成绩单入口", false, []string{}},
	{"course-score-detail", "课程", "个人学习记录", "GET", "/meol/common/newscoremanagement/stu_course_detail.jsp", "个人课程学习记录和成绩分析", false, []string{}},
	{"course-feedback", "课程", "随堂反馈", "GET", "/meol/common/unitfeedback/stu/feedback_list.jsp", "随堂建议问卷", false, []string{}},
	{"course-notes", "课程", "学习笔记", "GET", "/meol/common/notebook/column_notebook_share.jsp", "教师/学生笔记集", false, []string{}},
	{"course-note-write", "课程", "写学习笔记", "GET", "/meol/common/notebook/notebook_write.jsp", "创建学习笔记", false, []string{}},
	{"course-note-compose", "课程", "课程笔记编辑", "GET", "/meol/common/notebook/course_write_note.jsp", "课程首页写笔记弹窗", false, []string{}},
	{"course-note-book", "课程", "课程笔记本", "GET", "/meol/common/notebook/course_notebook.jsp", "课程首页查看笔记弹窗", false, []string{}},
	{"course-mailbox", "课程", "站内邮箱", "GET", "/meol/common/mail/inputbox.jsp", "站内邮箱收件箱弹窗", false, []string{}},
	{"course-forum-frame", "课程", "讨论区弹窗", "GET", "/meol/common/faq/forum.jsp", "课程首页讨论区弹窗", false, []string{}},
	{"course-livevod", "课程", "直播预约", "GET", "/meol/livevod/liveVodAppointmentStuList.do", "课程直播预约", false, []string{}},
	{"course-ccvod", "课程", "CC直播频道", "GET", "/meol/ccvod/ccVodChannelStuList.do", "CC直播频道", false, []string{}},
	{"course-netmeeting", "课程", "网络会议", "GET", "/meol/netmeeting/netMeetingPreAddUser.do", "课程网络会议", false, []string{}},
	{"course-tencent-meeting", "课程", "腾讯会议", "GET", "/meol/tencentmeeting/tenCentMeetingPreAddUser.do", "课程腾讯会议", false, []string{}},
	{"security-send-sms", "个人", "发送手机验证码", "GET", "/meol/sendSms.do", "发送绑定手机验证码", false, []string{}},
	{"security-bind-mobile", "个人", "提交手机绑定", "GET", "/meol/bindMobileDo.do", "提交手机绑定验证码", false, []string{}},
	{"course-faq", "课程", "常见问题", "GET", "/meol/common/faq/course_tea_faq.jsp", "FAQ 分类、查询和推荐筛选", false, []string{}},
	{"course-faq-personal", "课程", "个人答疑问题", "GET", "/meol/common/faq/course_tea_maq.jsp", "个人答疑问题", false, []string{}},
	{"course-faq-detail", "课程", "常见问题详情", "GET", "/meol/common/faq/article.jsp", "FAQ 详情和评论", false, []string{}},
	{"course-forum-discuss", "课程", "讨论区版面", "GET", "/meol/common/faq/tea_discuss.jsp", "讨论区版面及主题列表", false, []string{}},
	{"bug-report", "公共组件", "问题反馈", "GET", "/meol/popups/bugreport_do.jsp", "向平台提交页面问题反馈", false, []string{}},
	{"system-faq", "公共组件", "系统帮助", "GET", "/meol/common/faq/sys_faq.jsp", "系统帮助和常见问题", false, []string{}},
	{"course-forum", "课程", "答疑讨论", "GET", "/meol/common/faq/forum_search.jsp", "讨论区搜索、排序和发帖", false, []string{}},
	{"course-thread", "课程", "讨论主题", "GET", "/meol/homepage/threadAction.do", "讨论主题和回复", false, []string{}},
	{"course-forum-post", "课程", "发表讨论", "GET", "/meol/common/faq/postArticle.jsp?opt=topost", "发表新话题/回复", false, []string{}},
	{"course-surveys", "课程", "课程问卷", "GET", "/meol/common/questionaire/stu_survey.jsp", "问卷列表、参加和结果", false, []string{}},
	{"course-survey", "课程", "问卷填写", "GET", "/meol/common/questionaire/survey.jsp", "填写课程问卷", false, []string{}},
	{"course-survey-result", "课程", "问卷结果", "GET", "/meol/common/questionaire/survey_result.jsp", "查看问卷结果", false, []string{}},
	{"course-questionbank", "课程", "试题试卷库", "GET", "/meol/common/question/questionbank/student/list.jsp", "按题型/章节/知识点检索试题", false, []string{}},
	{"course-questions", "课程", "试题库", "GET", "/meol/common/question/questionbank/student/list.jsp", "试题库列表", false, []string{}},
	{"course-papers", "课程", "试卷库", "GET", "/meol/common/question/paperbank/student/list.jsp", "试卷库列表、下载和答案", false, []string{}},
	{"course-tests", "课程", "在线测试", "GET", "/meol/common/question/test/student/list.jsp", "测试列表和结果", false, []string{}},
	{"course-test", "课程", "开始在线测试", "GET", "/meol/common/question/test/student/stu_qtest_navigate.jsp", "在线测试导航", false, []string{}},
	{"course-test-photo", "课程", "测试照片上传", "GET", "/meol/test/userTestPhoto.do", "测试过程照片上传", false, []string{}},
	{"course-issues", "课程", "研究型教学主题", "GET", "/meol/issueteach/issue/myissue/my_issue.jsp", "我的研究型教学主题", false, []string{}},
	{"course-issue-list", "课程", "研究型教学主题列表", "GET", "/meol/issueteach/issue/myissue/issue_list.jsp?_style=new03", "全部研究型教学主题", false, []string{}},
	{"course-structures", "课程", "播课单元结构", "GET", "/meol/microlessonunit/previewListCourseStructure.do", "播课单元结构列表", false, []string{}},
	{"homework-app", "作业", "课程作业应用", "GET", "/meol/common/homework.html?showType=null", "作业 SPA", false, []string{}},
	{"homework-info", "作业", "作业信息", "GET", "/meol/common/homework.html?showType=null", "作业内容和提交规则", false, []string{}},
	{"homework-submit", "作业", "作业提交", "GET", "/meol/common/homework.html?showType=null", "作业答案编辑、提交和订正", false, []string{}},
	{"homework-result", "作业", "作业结果", "GET", "/meol/common/homework.html?showType=null", "成绩、互评和评论", false, []string{}},
	{"ueditor-content", "公共组件", "富文本内容框架", "GET", "/meol/common/ueditor/content.html", "平台富文本内容 iframe", false, []string{}},
}

var teachingAPIs = []teachingCatalogItem{
	{"homework-stu-user-login", "", "作业学生会话初始化", "GET", "/meol/hw/stu/userLogin.do", "作业学生会话初始化", false, []string{}},
	{"homework-stu-list", "", "学生作业列表", "GET", "/meol/hw/stu/hwStuHwtList.do", "学生作业列表", false, []string{}},
	{"homework-stu-submit", "", "读取作业提交页", "GET", "/meol/hw/stu/hwStuSubmit.do", "读取作业提交页", false, []string{}},
	{"homework-stu-submit-do", "", "提交或更新作业答案", "POST", "/meol/hw/stu/hwStuSubmitDo.do", "提交或更新作业答案", true, []string{}},
	{"homework-stu-answer-view", "", "查看已提交答案/订正", "GET", "/meol/hw/stu/hwTaskAnswerView.do", "查看已提交答案/订正", false, []string{}},
	{"homework-stu-review-list", "", "我的互评任务", "GET", "/meol/hw/stu/hwReviewList.do", "我的互评任务", false, []string{}},
	{"homework-stu-mutual-list", "", "互评结果", "GET", "/meol/hw/stu/hwMutualList.do", "互评结果", false, []string{}},
	{"homework-stu-mutual-review", "", "互评填写页", "GET", "/meol/hw/stu/hwMutualReview.do", "互评填写页", false, []string{}},
	{"homework-stu-review-details", "", "学生互评详情", "GET", "/meol/hw/stu/hwStuReviewDetails.do", "学生互评详情", false, []string{}},
	{"homework-stu-review-save", "", "保存自评/互评", "POST", "/meol/hw/stu/hwStuReviewSave.do", "保存自评/互评", true, []string{}},
	{"homework-stu-score", "", "查看作业成绩", "GET", "/meol/hw/stu/hwShowScore.do", "查看作业成绩", false, []string{}},
	{"homework-stu-review-show", "", "查看教师/自评/互评详情", "GET", "/meol/hw/stu/hwShowReviewDetails.do", "查看教师/自评/互评详情", false, []string{}},
	{"homework-stu-complain", "", "作业评价申诉", "POST", "/meol/hw/stu/hwShowReviewDetails.do", "作业评价申诉", true, []string{}},
	{"homework-stu-hook-up", "", "学生作业关联", "GET", "/meol/hw/stu/hwStuHookUp.do", "学生作业关联", false, []string{}},
	{"homework-vis-list", "", "访客作业列表", "GET", "/meol/hw/vis/hwVisHwtList.do", "访客作业列表", false, []string{}},
	{"homework-vis-hook-up", "", "访客作业关联", "GET", "/meol/hw/vis/hwVisHookUp.do", "访客作业关联", false, []string{}},
	{"homework-tea-login", "", "教师作业会话初始化", "GET", "/meol/hw/tea/userLogin.do", "教师作业会话初始化", false, []string{}},
	{"homework-tea-untreated-complain", "", "未处理申诉", "GET", "/meol/hw/tea/hwUntreatedComplainList.do", "未处理申诉", false, []string{}},
	{"homework-tea-task-list", "", "教师作业任务列表", "GET", "/meol/hw/tea/zyHwTaskList.do", "教师作业任务列表", false, []string{}},
	{"homework-tea-task-info", "", "作业任务信息", "GET", "/meol/hw/tea/hwTaskInfo.do", "作业任务信息", false, []string{}},
	{"homework-tea-add-task", "", "新增作业任务", "POST", "/meol/hw/tea/addHwTask.do", "新增作业任务", true, []string{}},
	{"homework-tea-update-task", "", "更新作业任务", "POST", "/meol/hw/tea/updateHwTask.do", "更新作业任务", true, []string{}},
	{"homework-tea-delete-task", "", "删除作业任务", "POST", "/meol/hw/tea/delHwTask.do", "删除作业任务", true, []string{}},
	{"homework-tea-package-task", "", "打包作业", "POST", "/meol/hw/tea/packageTask.do", "打包作业", true, []string{}},
	{"homework-tea-group-list", "", "作业分组", "GET", "/meol/hw/tea/taskGroupList.do", "作业分组", false, []string{}},
	{"homework-tea-comment-info", "", "批语信息", "GET", "/meol/hw/tea/taskCommentInfo.do", "批语信息", false, []string{}},
	{"homework-tea-set-comment", "", "设置批语", "POST", "/meol/hw/tea/setTaskComment.do", "设置批语", true, []string{}},
	{"homework-tea-update-setting", "", "更新作业设置", "POST", "/meol/hw/tea/updateTaskSetting.do", "更新作业设置", true, []string{}},
	{"homework-tea-review-manage", "", "作业批阅管理", "GET", "/meol/hw/tea/hwReviewManage.do", "作业批阅管理", false, []string{}},
	{"homework-tea-search-student", "", "搜索学生作业", "GET", "/meol/hw/tea/hwSearchStuHwa.do", "搜索学生作业", false, []string{}},
	{"homework-tea-update-review-setting", "", "更新批阅设置", "POST", "/meol/hw/tea/hwUpdateSett.do", "更新批阅设置", true, []string{}},
	{"homework-tea-import-batch", "", "批量导入作业", "POST", "/meol/hw/tea/hwImportBatchHwa.do", "批量导入作业", true, []string{}},
	{"homework-tea-no-submit", "", "未提交学生", "GET", "/meol/hw/tea/hwStuNoSubmit.do", "未提交学生", false, []string{}},
	{"homework-tea-remove-list", "", "移除列表", "GET", "/meol/hw/tea/hwRemoveList.do", "移除列表", false, []string{}},
	{"homework-tea-update-mark", "", "更新成绩", "POST", "/meol/hw/tea/hwUpdateMark.do", "更新成绩", true, []string{}},
	{"homework-tea-answer-all", "", "全部答案", "GET", "/meol/hw/tea/hwAnswerAllList.do", "全部答案", false, []string{}},
	{"homework-tea-write", "", "教师批阅页", "GET", "/meol/hw/tea/hwWriteByTea.do", "教师批阅页", false, []string{}},
	{"homework-tea-write-do", "", "提交教师批阅", "POST", "/meol/hw/tea/hwWriteByTeaDo.do", "提交教师批阅", true, []string{}},
	{"homework-tea-review", "", "教师互评管理", "GET", "/meol/hw/tea/hwTeaReview.do", "教师互评管理", false, []string{}},
	{"homework-tea-review-details", "", "教师批阅详情", "GET", "/meol/hw/tea/hwTeaReviewDetails.do", "教师批阅详情", false, []string{}},
	{"homework-tea-review-save", "", "保存教师互评", "POST", "/meol/hw/tea/hwTeaReviewSave.do", "保存教师互评", true, []string{}},
	{"homework-tea-mutual-mark", "", "学生互评成绩", "GET", "/meol/hw/tea/hwStuMutualMarkList.do", "学生互评成绩", false, []string{}},
	{"homework-tea-mutual-details", "", "学生互评详情", "GET", "/meol/hw/tea/hwStuMutualDetails.do", "学生互评详情", false, []string{}},
	{"homework-tea-download-zip", "", "下载作业压缩包", "GET", "/meol/hw/tea/downLoadTaskZip.do", "下载作业压缩包", false, []string{}},
	{"homework-tea-standard-list", "", "评分标准列表", "GET", "/meol/hw/tea/zyStandardList.do", "评分标准列表", false, []string{}},
	{"homework-tea-standard-delete", "", "删除评分标准", "POST", "/meol/hw/tea/delZyStandard.do", "删除评分标准", true, []string{}},
	{"homework-tea-standard-item-delete", "", "删除评分标准项", "POST", "/meol/hw/tea/delZyStandardItem.do", "删除评分标准项", true, []string{}},
	{"homework-tea-standard-add", "", "新增评分标准", "POST", "/meol/hw/tea/addZyStandard.do", "新增评分标准", true, []string{}},
	{"homework-tea-standard-status", "", "改变评分标准状态", "POST", "/meol/hw/tea/changeZyStandardStatus.do", "改变评分标准状态", true, []string{}},
	{"homework-tea-standard-item-add", "", "新增评分标准项", "POST", "/meol/hw/tea/addZyStandardItem.do", "新增评分标准项", true, []string{}},
	{"homework-tea-standard-info", "", "评分标准详情", "GET", "/meol/hw/tea/zyStandardInfo.do", "评分标准详情", false, []string{}},
	{"homework-tea-list", "", "教师作业列表", "GET", "/meol/hw/tea/hwList.do", "教师作业列表", false, []string{}},
	{"homework-tea-delete", "", "删除教师作业", "POST", "/meol/hw/tea/delHw.do", "删除教师作业", true, []string{}},
	{"homework-tea-view", "", "教师作业详情", "GET", "/meol/hw/tea/hwView.do", "教师作业详情", false, []string{}},
	{"homework-tea-add-zy", "", "新增作业", "POST", "/meol/hw/tea/addZyHw.do", "新增作业", true, []string{}},
	{"homework-tea-standard-score-list", "", "按分数查看评分标准", "GET", "/meol/hw/tea/zyStandardByScoreList.do", "按分数查看评分标准", false, []string{}},
	{"homework-tea-select-mark", "", "选择批阅", "GET", "/meol/hw/tea/hwSelectMark.do", "选择批阅", false, []string{}},
	{"homework-student-stat", "", "作业成绩统计", "GET", "/meol/hw/stu/hwStat.do", "作业成绩统计", false, []string{}},
	{"homework-student-stat-grade", "", "作业等级统计", "GET", "/meol/hw/stu/hwStatGrade.do", "作业等级统计", false, []string{}},
	{"homework-export-grade", "", "导出作业成绩", "GET", "/meol/hw/tea/exportHwTaskGrade.do", "导出作业成绩", false, []string{}},
	{"homework-export-student-score", "", "导出学生成绩", "GET", "/meol/hw/tea/hwExportStuScore.do", "导出学生成绩", false, []string{}},
	{"homework-export-not-submit", "", "导出未提交学生", "GET", "/meol/hw/tea/hwExportStuNotSubmit.do", "导出未提交学生", false, []string{}},
	{"homework-answer-export-demo", "", "导出答案模板", "GET", "/meol/hw/tea/hwAnswerExportDemo.do", "导出答案模板", false, []string{}},
	{"calendar-month", "", "月日历数据", "GET", "/meol/common/calendar/month.jsp", "月日历数据", false, []string{}},
	{"calendar-date", "", "日日历数据", "GET", "/meol/common/calendar/date.jsp", "日日历数据", false, []string{}},
	{"course-apply", "", "可申请课程查询", "GET", "/meol/lesson/applynewcourse_stu.jsp", "可申请课程查询", false, []string{}},
	{"course-summary", "", "可申请课程简介", "GET", "/meol/lesson/coursesum.jsp", "可申请课程简介", false, []string{}},
	{"course-join", "", "申请加入课程", "GET", "/meol/lesson/applyjoincourse.jsp", "申请加入课程", true, []string{}},
	{"course-archive", "", "历史课程", "GET", "/meol/archive/archiveCourseListByStu.do", "历史课程", false, []string{}},
	{"mail", "", "站内邮箱入口", "GET", "/meol/common/mail/index.jsp", "站内邮箱入口", false, []string{}},
	{"mail-inbox", "", "收件箱", "GET", "/meol/common/mail/inputbox.jsp", "收件箱", false, []string{}},
	{"mail-sent", "", "已发送邮件", "GET", "/meol/common/mail/sent.jsp", "已发送邮件", false, []string{}},
	{"mail-draft", "", "草稿箱", "GET", "/meol/common/mail/draft.jsp", "草稿箱", false, []string{}},
	{"mail-trash", "", "垃圾箱", "GET", "/meol/common/mail/garbage.jsp", "垃圾箱", false, []string{}},
	{"mail-folders", "", "邮箱文件夹管理", "GET", "/meol/common/mail/managefolder.jsp", "邮箱文件夹管理", false, []string{}},
	{"mail-contacts", "", "邮箱联系人管理", "GET", "/meol/common/mail/managecontact.jsp", "邮箱联系人管理", false, []string{}},
	{"mail-compose", "", "写邮件页面", "GET", "/meol/common/mail/composemail.jsp", "写邮件页面", false, []string{}},
	{"mail-edit-folder", "", "编辑邮箱文件夹页面", "GET", "/meol/common/mail/editfolder.jsp", "编辑邮箱文件夹页面", false, []string{}},
	{"mail-edit-contact", "", "编辑邮箱联系人页面", "GET", "/meol/common/mail/editcontact.jsp", "编辑邮箱联系人页面", false, []string{}},
	{"mail-search", "", "搜索邮件", "POST", "/meol/common/mail/search.jsp", "搜索邮件", false, []string{}},
	{"mail-message-action", "", "邮件删除、标记和移动", "POST", "/meol/common/mail/inputbox.jsp", "邮件删除、标记和移动", true, []string{}},
	{"mail-trash-empty", "", "清空垃圾箱", "GET", "/meol/common/mail/garbage.jsp?action=empty", "清空垃圾箱", true, []string{}},
	{"mail-folder-action", "", "邮箱文件夹操作", "POST", "/meol/common/mail/managefolder.jsp", "邮箱文件夹操作", true, []string{}},
	{"mail-folder-empty", "", "清空邮箱文件夹", "GET", "/meol/common/mail/managefolder.jsp?action=_empty", "清空邮箱文件夹", true, []string{}},
	{"mail-contact-action", "", "联系人删除和移动", "POST", "/meol/common/mail/managecontact.jsp", "联系人删除和移动", true, []string{}},
	{"mail-send", "", "发送邮件", "POST", "/meol/common/mail/composemail.jsp", "发送邮件", true, []string{}},
	{"mail-save", "", "保存邮件草稿", "POST", "/meol/common/mail/composemail.jsp", "保存邮件草稿", true, []string{}},
	{"mail-folder-save", "", "保存邮箱文件夹", "POST", "/meol/common/mail/editfolder.jsp", "保存邮箱文件夹", true, []string{}},
	{"mail-contact-save", "", "保存邮箱联系人", "POST", "/meol/common/mail/editcontact.jsp", "保存邮箱联系人", true, []string{}},
	{"mail-message", "", "邮件详情", "GET", "/meol/common/mail/mail.jsp", "邮件详情", false, []string{}},
	{"mail-settings", "", "邮箱设置", "GET", "/meol/common/mail/mailsetting.jsp", "邮箱设置", false, []string{}},
	{"mail-settings-save", "", "保存邮箱设置", "POST", "/meol/common/mail/mailsetting.jsp", "保存邮箱设置", true, []string{}},
	{"mail-contact-search", "", "联系人搜索详情", "GET", "/meol/common/mail/search_info.jsp", "联系人搜索详情", false, []string{}},
	{"student-info-edit", "", "编辑学生信息页面", "GET", "/meol/popups/student_info_modify.jsp", "编辑学生信息页面", false, []string{}},
	{"student-info-update", "", "更新邮箱和电话", "POST", "/meol/popups/student_info_modify_do.jsp", "更新邮箱和电话", true, []string{}},
	{"password", "", "修改密码页面", "GET", "/meol/popups/password.jsp", "修改密码页面", false, []string{}},
	{"password-update", "", "提交密码修改", "POST", "/meol/popups/password_do.jsp", "提交密码修改", true, []string{}},
	{"security-question", "", "安全问题设置页面", "GET", "/meol/validateQuestion.do", "安全问题设置页面", false, []string{}},
	{"security-question-update", "", "提交安全问题", "POST", "/meol/validateQuestionDo.do", "提交安全问题", true, []string{}},
	{"security-email-verify", "", "发送邮箱验证", "GET", "/meol/validateEmailSend.do", "发送邮箱验证", true, []string{}},
	{"security-mobile", "", "绑定手机页面", "GET", "/meol/lifelong/user/bind_mobile.jsp", "绑定手机页面", false, []string{}},
	{"bind-mobile-reminder", "", "绑定手机提醒页面", "GET", "/meol/lifelong/user/bind_mobile_ignore.jsp", "绑定手机提醒页面", false, []string{}},
	{"security-send-sms", "", "发送手机验证码", "POST", "/meol/sendSms.do", "发送手机验证码", true, []string{}},
	{"security-bind-mobile", "", "提交手机绑定", "POST", "/meol/bindMobileDo.do", "提交手机绑定", true, []string{}},
	{"mobile-login", "", "手机验证码登录", "POST", "/meol/mobileLogin.do", "手机验证码登录", true, []string{}},
	{"bind-mobile-ignore", "", "暂不绑定手机", "GET", "/meol/bindMobileIgnore.do", "暂不绑定手机", true, []string{}},
	{"home-notifications-all", "", "首页全部通知", "GET", "/meol/homepage/common/inform_all.jsp", "首页全部通知", false, []string{}},
	{"course-search", "", "课程名称/编号查询", "POST", "/meol/course.do", "课程名称/编号查询", false, []string{}},
	{"course-departments", "", "课程院系列表", "GET", "/meol/allDepartment.do", "课程院系列表", false, []string{}},
	{"course-curriculum", "", "培养方案课程表", "GET", "/meol/homepage/V8/include/course_curriculum.jsp", "培养方案课程表", false, []string{}},
	{"password-recovery", "", "找回密码页面", "GET", "/meol/findPasswdIndex.do", "找回密码页面", false, []string{}},
	{"password-email-pre", "", "邮箱找回密码页面", "GET", "/meol/findPasswdMailBoxPreAccount.do", "邮箱找回密码页面", false, []string{}},
	{"password-email-account", "", "提交邮箱身份验证", "POST", "/meol/findPasswdMailBoxAccount.do", "提交邮箱身份验证", true, []string{}},
	{"password-email-receive", "", "接收重置邮件页面", "GET", "/meol/findPasswdMailBoxReceive.do", "接收重置邮件页面", false, []string{}},
	{"password-question-pre", "", "提示问题找回密码页面", "GET", "/meol/findPasswdQuestionPreAccount.do", "提示问题找回密码页面", false, []string{}},
	{"password-question-account", "", "提交提示问题验证", "POST", "/meol/findPasswdQuestionAccount.do", "提交提示问题验证", true, []string{}},
	{"password-question-reset", "", "提示问题重置密码页面", "GET", "/meol/findPasswdQuestionPreReset.do", "提示问题重置密码页面", false, []string{}},
	{"password-captcha", "", "获取找回密码验证码", "GET", "/meol/getCaptcha.do", "获取找回密码验证码", false, []string{}},
	{"platform-login", "", "旧版平台登录表单", "POST", "/meol/loginCheck.do", "旧版平台登录表单", true, []string{}},
	{"learning-menu", "", "学习管理菜单", "GET", "/meol/left_v8.jsp", "学习管理菜单", false, []string{}},
	{"research-menu", "", "研究型教学菜单", "GET", "/meol/issueteach/left.jsp", "研究型教学菜单", false, []string{}},
	{"excellent-menu", "", "精品课程菜单", "GET", "/meol/jpk/student/left.jsp", "精品课程菜单", false, []string{}},
	{"podcast-menu", "", "教学播客菜单", "GET", "/meol/common/vblog/stu_left.jsp", "教学播客菜单", false, []string{}},
	{"podcast-inner", "", "教学播客首页", "GET", "/meol/common/vblog/inner_index.jsp", "教学播客首页", false, []string{}},
	{"consultation-menu", "", "应用咨询菜单", "GET", "/meol/popups/teach_v8/student_popups.jsp", "应用咨询菜单", false, []string{}},
	{"consultation", "", "应用咨询内容", "GET", "/meol/popups/student_1.htm", "应用咨询内容", false, []string{}},
	{"department-teachers", "", "教研室教师列表", "GET", "/meol/teacher.do", "教研室教师列表", false, []string{}},
	{"honor-courses", "", "荣誉课程列表", "GET", "/meol/honLesson.do", "荣誉课程列表", false, []string{}},
	{"honor-teachers", "", "荣誉教师列表", "GET", "/meol/honTeacher.do", "荣誉教师列表", false, []string{}},
	{"global-logout", "", "退出教学平台", "GET", "/meol/homepage/V8/include/logout.jsp", "退出教学平台", false, []string{}},
	{"public-course", "", "公开课程首页", "GET", "/meol/homepage/course/course_index.jsp", "公开课程首页", false, []string{}},
	{"course-lesson-home", "", "课程学习首页", "GET", "/meol/jpk/course/layout/lesson/index.jsp", "课程学习首页", false, []string{}},
	{"course-default", "", "课程介绍首页", "GET", "/meol/jpk/course/layout/newpage/default_demonstrate.jsp", "课程介绍首页", false, []string{}},
	{"course-unit-blank", "", "单元学习容器", "GET", "/meol/jpk/course/layout/_blank.jsp", "单元学习容器", false, []string{}},
	{"course-qrcode", "", "课程二维码", "GET", "/meol/lesson/qrcode.jsp", "课程二维码", false, []string{}},
	{"course-logout", "", "退出教学平台", "GET", "/meol/homepage/common/logout.jsp", "退出教学平台", false, []string{}},
	{"course-user-stat", "", "课程首页统计数据", "POST", "/meol/jpk/course/userLessonStat.jsp", "课程首页统计数据", false, []string{}},
	{"course-online-heartbeat", "", "记录课程在线时长", "POST", "/meol/lesson/onlinetime_listener.jsp", "记录课程在线时长", true, []string{}},
	{"online-help", "", "在线帮助", "GET", "/meol/common/help/help.jsp", "在线帮助", false, []string{}},
	{"course-note-compose", "", "课程首页写笔记", "GET", "/meol/common/notebook/course_write_note.jsp", "课程首页写笔记", false, []string{}},
	{"course-note-book", "", "课程首页笔记本", "GET", "/meol/common/notebook/course_notebook.jsp", "课程首页笔记本", false, []string{}},
	{"course-mailbox", "", "站内邮箱", "GET", "/meol/common/mail/inputbox.jsp", "站内邮箱", false, []string{}},
	{"course-forum-frame", "", "课程首页讨论区", "GET", "/meol/common/faq/forum.jsp", "课程首页讨论区", false, []string{}},
	{"course-livevod", "", "直播预约", "GET", "/meol/livevod/liveVodAppointmentStuList.do", "直播预约", false, []string{}},
	{"course-ccvod", "", "CC直播频道", "GET", "/meol/ccvod/ccVodChannelStuList.do", "CC直播频道", false, []string{}},
	{"course-netmeeting", "", "网络会议", "GET", "/meol/netmeeting/netMeetingPreAddUser.do", "网络会议", false, []string{}},
	{"course-tencent-meeting", "", "腾讯会议", "GET", "/meol/tencentmeeting/tenCentMeetingPreAddUser.do", "腾讯会议", false, []string{}},
	{"podcast-search", "", "播客筛选查询", "POST", "/meol/custom.do?menuId=4", "播客筛选查询", false, []string{}},
	{"activity-search", "", "研究型教学查询", "POST", "/meol/activity.do?menuId=3", "研究型教学查询", false, []string{}},
	{"activity-course-list", "", "研究型教学课程列表", "GET", "/meol/homepage/V8/include/issue_course_list.jsp", "研究型教学课程列表", false, []string{}},
	{"research-public", "", "校级研究型教学主题", "GET", "/meol/issueteach/issue/pubissue_list.jsp", "校级研究型教学主题", false, []string{}},
	{"research-course-list", "", "课程研究型教学", "POST", "/meol/issueteach/issue/courseissue_list_stu.jsp", "课程研究型教学", false, []string{}},
	{"research-my-all", "", "我的研究型教学", "POST", "/meol/issueteach/issue/myissue/my_issue_allcourse.jsp", "我的研究型教学", false, []string{}},
	{"excellent-apply", "", "精品课程申报列表", "GET", "/meol/jpk/teacher/ela_sect_apply.jsp", "精品课程申报列表", false, []string{}},
	{"excellent-course-list", "", "历年精品课程列表", "GET", "/meol/jpk/teacher/ela_sect.jsp", "历年精品课程列表", false, []string{}},
	{"excellent-course-manage", "", "申报期课程列表", "POST", "/meol/jpk/teacher/coursemanage_byselect.jsp", "申报期课程列表", false, []string{}},
	{"excellent-course", "", "申报课程浏览", "GET", "/meol/jpk/course/index.jsp", "申报课程浏览", false, []string{}},
	{"social-friend-search", "", "社区找人", "POST", "/meol/social/friendSearch.do", "社区找人", false, []string{}},
	{"social-course-search", "", "社区找课程", "GET", "/meol/social/coursesSearch.do", "社区找课程", false, []string{}},
	{"social-circle-search", "", "社区找圈子", "GET", "/meol/social/studyCircleSearch.do", "社区找圈子", false, []string{}},
	{"social-circle", "", "学习圈详情", "GET", "/meol/social/studyCircleInfo.do", "学习圈详情", false, []string{}},
	{"social-circle-list", "", "我的学习圈", "GET", "/meol/social/studyCircleList.do", "我的学习圈", false, []string{}},
	{"social-person", "", "社区个人主页", "GET", "/meol/social/viewPersonInfo.do", "社区个人主页", false, []string{}},
	{"social-news", "", "社区动态", "GET", "/meol/social/listNews.do", "社区动态", false, []string{}},
	{"social-news-more", "", "加载更多社区动态", "POST", "/meol/social/listNewsMore.do", "加载更多社区动态", false, []string{}},
	{"social-topics", "", "个人话题", "GET", "/meol/social/listTopics.do", "个人话题", false, []string{}},
	{"social-attention", "", "关注列表", "GET", "/meol/social/listAttention.do", "关注列表", false, []string{}},
	{"social-attention-more", "", "加载更多关注", "POST", "/meol/social/listAttentionMore.do", "加载更多关注", false, []string{}},
	{"social-fans", "", "粉丝列表", "GET", "/meol/social/listMyFans.do", "粉丝列表", false, []string{}},
	{"social-new-circle", "", "创建圈子页面", "GET", "/meol/social/preAddStudyCircle.do", "创建圈子页面", false, []string{}},
	{"social-edit-person", "", "编辑社区资料页面", "GET", "/meol/social/preUpdPersonInfo.do", "编辑社区资料页面", false, []string{}},
	{"social-update-person", "", "更新社区个人资料", "POST", "/meol/social/updPersonInfo.do", "更新社区个人资料", true, []string{}},
	{"social-add-message", "", "发布社区动态", "POST", "/meol/social/addMessage.do", "发布社区动态", true, []string{}},
	{"social-add-topic-reply", "", "发表评论或回复", "POST", "/meol/social/addTopicReply.do", "发表评论或回复", true, []string{}},
	{"social-add-attention", "", "添加关注", "POST", "/meol/social/addAttention.do", "添加关注", true, []string{}},
	{"social-delete-attention", "", "取消关注", "POST", "/meol/social/deleteAttention.do", "取消关注", true, []string{}},
	{"social-add-circle-user", "", "加入学习圈", "POST", "/meol/social/addCircleUser.do", "加入学习圈", true, []string{}},
	{"social-exit-circle", "", "退出学习圈", "POST", "/meol/social/circleUserExit.do", "退出学习圈", true, []string{}},
	{"social-add-circle", "", "创建学习圈", "POST", "/meol/social/addStudyCircle.do", "创建学习圈", true, []string{}},
	{"social-delete-circle", "", "删除学习圈", "POST", "/meol/social/deleteStudyCircle.do", "删除学习圈", true, []string{}},
	{"social-delete-topic", "", "删除社区话题", "POST", "/meol/social/deleteMessage.do", "删除社区话题", true, []string{}},
	{"social-delete-topic-reply", "", "删除话题回复", "POST", "/meol/social/deleteTopicReply.do", "删除话题回复", true, []string{}},
	{"social-delete-news-topic", "", "删除动态和话题", "POST", "/meol/social/deleteNewsAndTopic.do", "删除动态和话题", true, []string{}},
	{"social-delete-fan", "", "删除粉丝", "POST", "/meol/social/deleteMyFans.do", "删除粉丝", true, []string{}},
	{"social-upload-photo", "", "上传社区头像/图片", "POST", "/meol/social/newUploadPhotos.do", "上传社区头像/图片", true, []string{}},
	{"social-upload-temp", "", "上传社区图片临时文件", "POST", "/meol/social/uploadImg.do", "上传社区图片临时文件", true, []string{}},
	{"social-delete-temp", "", "删除社区图片临时文件", "POST", "/meol/social/deleteImg.do", "删除社区图片临时文件", true, []string{}},
	{"social-date-picker", "", "社区日期选择器", "GET", "/meol/lifelong/social/My97DatePicker.htm", "社区日期选择器", false, []string{}},
	{"social-download-file", "", "下载社区文件", "GET", "/meol/downloadTheolFile.do", "下载社区文件", false, []string{}},
	{"course-jump", "", "从社区进入课程", "GET", "/meol/lesson/mainJumpPage.jsp", "从社区进入课程", false, []string{}},
	{"social-help", "", "社区在线帮助", "GET", "/meol/common/help/help.jsp", "社区在线帮助", false, []string{}},
	{"course-notices", "", "课程通知列表", "GET", "/meol/common/inform/index_stu.jsp", "课程通知列表", false, []string{}},
	{"course-notice-detail", "", "通知详情", "GET", "/meol/common/inform/message_content.jsp", "通知详情", false, []string{}},
	{"course-forum-search", "", "讨论区搜索", "POST", "/meol/common/faq/forum_search.jsp", "讨论区搜索", false, []string{}},
	{"course-forum-post", "", "发帖/回复", "POST", "/meol/common/faq/postArticle.jsp?opt=topost", "发帖/回复", true, []string{}},
	{"course-forum-sort", "", "讨论排序/分页", "GET", "/meol/homepage/forumAction.do", "讨论排序/分页", false, []string{}},
	{"course-thread", "", "讨论主题详情", "GET", "/meol/homepage/threadAction.do", "讨论主题详情", false, []string{}},
	{"course-faq", "", "FAQ 查询", "GET", "/meol/common/faq/course_tea_faq.jsp", "FAQ 查询", false, []string{}},
	{"course-faq-personal", "", "个人答疑", "GET", "/meol/common/faq/course_tea_maq.jsp", "个人答疑", false, []string{}},
	{"course-faq-detail", "", "FAQ 详情", "GET", "/meol/common/faq/article.jsp", "FAQ 详情", false, []string{}},
	{"course-forum-discuss", "", "讨论区版面", "GET", "/meol/common/faq/tea_discuss.jsp", "讨论区版面", false, []string{}},
	{"bug-report", "", "提交问题反馈", "POST", "/meol/popups/bugreport_do.jsp", "提交问题反馈", true, []string{}},
	{"system-faq", "", "系统帮助", "POST", "/meol/common/faq/sys_faq.jsp", "系统帮助", false, []string{}},
	{"course-survey-list", "", "问卷列表", "POST", "/meol/common/questionaire/stu_survey.jsp", "问卷列表", false, []string{}},
	{"course-survey", "", "填写问卷", "GET", "/meol/common/questionaire/survey.jsp", "填写问卷", false, []string{}},
	{"course-survey-result", "", "问卷结果", "GET", "/meol/common/questionaire/survey_result.jsp", "问卷结果", false, []string{}},
	{"course-question-list", "", "题库查询", "POST", "/meol/common/question/questionbank/student/list.jsp", "题库查询", false, []string{}},
	{"course-paper-list", "", "试卷库查询", "GET", "/meol/common/question/paperbank/student/list.jsp", "试卷库查询", false, []string{}},
	{"course-test-list", "", "在线测试查询", "GET", "/meol/common/question/test/student/list.jsp", "在线测试查询", false, []string{}},
	{"course-test-navigate", "", "在线测试导航", "GET", "/meol/common/question/test/student/stu_qtest_navigate.jsp", "在线测试导航", false, []string{}},
	{"course-test-photo", "", "上传测试照片", "POST", "/meol/test/userTestPhoto.do", "上传测试照片", true, []string{}},
	{"course-resource-search", "", "课程资源搜索", "GET", "/meol/common/script/search.jsp", "课程资源搜索", false, []string{}},
	{"course-resource-list", "", "课程资源列表", "GET", "/meol/common/script/listview.jsp", "课程资源列表", false, []string{}},
	{"course-resource-preview", "", "预览/下载课程资源", "GET", "/meol/common/script/preview/download_preview.jsp", "预览/下载课程资源", false, []string{}},
	{"course-resource-folder", "", "课程资源文件夹", "GET", "/meol/common/script/left.jsp", "课程资源文件夹", false, []string{}},
	{"course-micro-lessons", "", "教学播课", "GET", "/meol/microlessonunit/viewMicroLesson.do", "教学播课", false, []string{}},
	{"course-structure", "", "播课单元结构变更", "POST", "/meol/microlessonunit/deleteCourseStructure.do", "播课单元结构变更", true, []string{}},
	{"course-structure-list", "", "播课单元结构列表", "GET", "/meol/microlessonunit/previewListCourseStructure.do", "播课单元结构列表", false, []string{}},
	{"course-analytics", "", "学习分析", "GET", "/meol/jpk/course/blended_module/mod_la_stu.jsp", "学习分析", false, []string{}},
	{"course-analytics-info", "", "学习分析信息", "GET", "/meol/la/student/course_info.jsp", "学习分析信息", false, []string{}},
	{"course-analytics-chart", "", "学习分析图表", "GET", "/meol/la/student/script_view.jsp", "学习分析图表", false, []string{}},
	{"course-analytics-enter", "", "学习分析记录", "GET", "/meol/la/student/lesson_enter.jsp", "学习分析记录", false, []string{}},
	{"course-score", "", "课程成绩", "GET", "/meol/newscoremanagement/scoreView.do", "课程成绩", false, []string{}},
	{"course-score-detail", "", "个人学习记录", "GET", "/meol/common/newscoremanagement/stu_course_detail.jsp", "个人学习记录", false, []string{}},
	{"course-feedback", "", "随堂反馈", "GET", "/meol/common/unitfeedback/stu/feedback_list.jsp", "随堂反馈", false, []string{}},
	{"course-notes", "", "学习笔记查询", "POST", "/meol/common/notebook/column_notebook_share.jsp", "学习笔记查询", false, []string{}},
	{"course-note-write", "", "保存学习笔记", "POST", "/meol/common/notebook/notebook_write.jsp", "保存学习笔记", true, []string{}},
	{"podcast-detail", "", "播客详情", "GET", "/meol/common/vblog/videodetail.jsp", "播客详情", false, []string{}},
	{"podcast-play", "", "播客播放", "GET", "/meol/microlessonunit/podcast.do", "播客播放", false, []string{}},
	{"podcast-recommend", "", "推荐播客", "GET", "/meol/common/vblog/recommend.jsp", "推荐播客", true, []string{}},
	{"podcast-favorite", "", "收藏播客", "GET", "/meol/common/vblog/favorite/add_favorite.jsp", "收藏播客", true, []string{}},
	{"podcast-review", "", "播客评论", "POST", "/meol/common/vblog/reviewvideo.jsp", "播客评论", true, []string{}},
	{"podcast-list", "", "全校视频列表", "GET", "/meol/common/vblog/listvideo.jsp", "全校视频列表", false, []string{}},
	{"podcast-favorites", "", "我的播客收藏", "GET", "/meol/common/vblog/favorite/favorite_video.jsp", "我的播客收藏", false, []string{}},
	{"podcast-recent", "", "近期点播", "GET", "/meol/common/vblog/recentvideo.jsp", "近期点播", false, []string{}},
	{"podcast-favorite-delete", "", "删除播客收藏", "POST", "/meol/common/vblog/favorite/del_favorite.jsp", "删除播客收藏", true, []string{}},
	{"resource-detail", "", "资源详情", "GET", "/moocresource/search/browser.jsp", "资源详情", false, []string{}},
	{"resource-sso", "", "资源中心 SSO 交接", "POST", "/moocresource/eol_sso_new.jsp", "资源中心 SSO 交接", true, []string{}},
	{"resource-attribute", "", "资源属性", "GET", "/moocresource/banks/search/attribute.jsp", "资源属性", false, []string{}},
	{"resource-related", "", "相关资源", "GET", "/moocresource/banks/relateres.jsp", "相关资源", false, []string{}},
	{"resource-personal-list", "", "我的资源", "GET", "/moocresource/myres/resourceInfoList.do", "我的资源", false, []string{}},
	{"resource-login", "", "资源中心登录", "POST", "/moocresource/servlet/loginServlet", "资源中心登录", true, []string{}},
	{"resource-home-search", "", "资源首页搜索", "POST", "/moocresource/view/reslist.jsp", "资源首页搜索", false, []string{}},
	{"resource-list-frame", "", "资源列表框架", "GET", "/moocresource/resource/resourceInfoList.do", "资源列表框架", false, []string{}},
	{"resource-list-search", "", "我的资源筛选", "POST", "/moocresource/resource/resourceInfoList.do", "我的资源筛选", false, []string{}},
	{"resource-list-page", "", "我的资源分页", "POST", "/moocresource/resource/resourceInfoList.do", "我的资源分页", false, []string{}},
	{"resource-add", "", "添加资源页面", "GET", "/moocresource/resource/preAddResourceInfo.do", "添加资源页面", false, []string{}},
	{"resource-move-batch", "", "批量移动资源", "POST", "/moocresource/resource/moveResourceInfoByBatch.do", "批量移动资源", true, []string{}},
	{"resource-delete-batch", "", "批量删除资源", "POST", "/moocresource/resource/deleteResourceInfoByBatch.do", "批量删除资源", true, []string{}},
	{"resource-left", "", "资源空间菜单", "GET", "/moocresource/myres/left.jsp", "资源空间菜单", false, []string{}},
	{"resource-folders-frame", "", "资源目录框架", "GET", "/moocresource/resource/listMyFolder.do", "资源目录框架", false, []string{}},
	{"resource-favorites-frame", "", "收藏资源框架", "GET", "/moocresource/myres/favorite/favorite_detail.jsp", "收藏资源框架", false, []string{}},
	{"resource-follows-frame", "", "关注资源框架", "GET", "/moocresource/myres/attentionres/attentionres_list.jsp", "关注资源框架", false, []string{}},
	{"resource-comments-frame", "", "资源评论框架", "GET", "/moocresource/myres/myreview/reviewlist.jsp", "资源评论框架", false, []string{}},
	{"resource-shares-frame", "", "共享资源框架", "GET", "/moocresource/resource/listShareRes.do", "共享资源框架", false, []string{}},
	{"resource-personal-frame", "", "资源个人信息框架", "GET", "/moocresource/personalset/class_personal_info.jsp", "资源个人信息框架", false, []string{}},
	{"resource-view", "", "共享资源详情", "GET", "/moocresource/resource/viewResourceInfo.do", "共享资源详情", false, []string{}},
	{"resource-favorite", "", "收藏或取消收藏资源", "POST", "/moocresource/myres/favorite/favorite.jsp", "收藏或取消收藏资源", true, []string{}},
	{"resource-rate", "", "资源评分", "POST", "/moocresource/search/res_evaluate.jsp", "资源评分", true, []string{}},
	{"resource-download", "", "下载资源文件", "GET", "/moocresource/servlet/ResourceDownload", "下载资源文件", false, []string{}},
	{"resource-tag-exists", "", "检查资源标签", "POST", "/moocresource/taglibrary/tagExist.do", "检查资源标签", false, []string{}},
	{"resource-tag-add", "", "添加资源标签", "POST", "/moocresource/taglibrary/tagAdd.do", "添加资源标签", true, []string{}},
	{"folder-add", "", "添加资源目录页面", "GET", "/moocresource/resource/preAddFolder.do", "添加资源目录页面", false, []string{}},
	{"folder-update", "", "更新资源目录", "POST", "/moocresource/resource/updateMySelfFolder.do", "更新资源目录", true, []string{}},
	{"folder-share-batch", "", "共享或取消共享目录", "POST", "/moocresource/resource/shareFolderBatch.do", "共享或取消共享目录", true, []string{}},
	{"folder-list", "", "收藏夹目录管理", "GET", "/moocresource/resource/myfolder_list.jsp", "收藏夹目录管理", false, []string{}},
	{"follow-add", "", "添加资源关注页面", "GET", "/moocresource/myres/attentionres/attentionres_add.jsp", "添加资源关注页面", false, []string{}},
	{"resource-logout", "", "退出资源中心会话", "GET", "/moocresource/logout.jsp", "退出资源中心会话", false, []string{}},
	{"resource-folders", "", "我的资源文件夹", "GET", "/moocresource/myres/listMyFolder.do", "我的资源文件夹", false, []string{}},
	{"resource-favorites", "", "资源收藏", "GET", "/moocresource/myres/favorite_detail.jsp", "资源收藏", false, []string{}},
	{"resource-follows", "", "资源关注", "GET", "/moocresource/myres/attentionres_list.jsp", "资源关注", false, []string{}},
	{"resource-comments", "", "资源评论", "GET", "/moocresource/myres/reviewlist.jsp", "资源评论", false, []string{}},
	{"resource-shares", "", "共享资源", "GET", "/moocresource/myres/listShareRes.do", "共享资源", false, []string{}},
	{"resource-personal-info", "", "资源个人统计", "GET", "/moocresource/myres/class_personal_info.jsp", "资源个人统计", false, []string{}},
	{"resource-notifications", "", "资源通知", "GET", "/moocresource/common/inform/index_all.jsp", "资源通知", false, []string{}},
	{"resource-updates", "", "资源更新", "GET", "/moocresource/statistics/all_new_list.jsp", "资源更新", false, []string{}},
	{"resource-bank-subject-list", "", "资源库分类列表", "GET", "/moocresource/banks/search/bank_index.jsp", "资源库分类列表", false, []string{}},
	{"resource-bank-login", "", "资源库登录提示", "GET", "/moocresource/banks/login.jsp", "资源库登录提示", false, []string{}},
	{"resource-bank", "", "资源库首页", "GET", "/moocresource/banks/search/bank.jsp", "资源库首页", false, []string{}},
	{"resource-bank-left", "", "资源库分类菜单", "GET", "/moocresource/banks/search/left.jsp", "资源库分类菜单", false, []string{}},
	{"resource-bank-left-submenu", "", "资源库子分类菜单", "GET", "/moocresource/banks/search/left-submenu.jsp", "资源库子分类菜单", false, []string{}},
	{"resource-bank-list", "", "专题库资源查询", "POST", "/moocresource/banks/search/reslist.jsp", "专题库资源查询", false, []string{}},
	{"resource-bank-keyword", "", "专题库关键词查询", "POST", "/moocresource/courses/searchres.jsp", "专题库关键词查询", false, []string{}},
	{"resource-excellent-list", "", "精品课程查询", "POST", "/moocresource/courses/excellent/course_list_query.jsp", "精品课程查询", false, []string{}},
	{"resource-open-list", "", "全球开放课程查询", "POST", "/moocresource/courses/ocw/ocwcoursesearch.jsp", "全球开放课程查询", false, []string{}},
	{"resource-video-list", "", "公开视频查询", "POST", "/moocresource/courses/xiaoyouhui/video_list_query.jsp", "公开视频查询", false, []string{}},
	{"resource-mooc-list", "", "MOOC查询", "POST", "/moocresource/courses/xiaoyouhui/mooc_list_query.jsp", "MOOC查询", false, []string{}},
	{"resource-micro-list", "", "微课程查询", "POST", "/moocresource/courses/xiaoyouhui/micro_list_query.jsp", "微课程查询", false, []string{}},
	{"resource-tag-list", "", "标签资源列表", "GET", "/moocresource/courses/xiaoyouhui/searchresourcebytag.jsp", "标签资源列表", false, []string{}},
	{"resource-entry-detail", "", "外部条目资源详情", "GET", "/moocresource/search/browser_by_entry.jsp", "外部条目资源详情", false, []string{}},
}

var teachingActions = []teachingCatalogItem{
	{"global.search", "全局", "课程名称/编号搜索", "POST", "/meol/course.do", "课程名称/编号搜索", false, []string{"deptId", "s_keywordrealation", "s_keyword"}},
	{"global.course.departments", "全局", "读取课程院系列表", "GET", "/meol/allDepartment.do", "读取课程院系列表", false, []string{}},
	{"global.course.curriculum", "全局", "查看培养方案课程表", "GET", "/meol/homepage/V8/include/course_curriculum.jsp", "查看培养方案课程表", false, []string{"deptId", "majorid", "curriculumid"}},
	{"password.recovery.open", "全局", "打开找回密码", "GET", "/meol/findPasswdIndex.do", "打开找回密码", false, []string{}},
	{"password.email.open", "全局", "打开邮箱找回密码", "GET", "/meol/findPasswdMailBoxPreAccount.do", "打开邮箱找回密码", false, []string{}},
	{"password.email.verify", "全局", "提交邮箱身份验证", "POST", "/meol/findPasswdMailBoxAccount.do", "提交邮箱身份验证", true, []string{"username", "email", "imgcode"}},
	{"password.email.receive", "全局", "查看重置邮件结果", "GET", "/meol/findPasswdMailBoxReceive.do", "查看重置邮件结果", false, []string{}},
	{"password.question.open", "全局", "打开提示问题找回密码", "GET", "/meol/findPasswdQuestionPreAccount.do", "打开提示问题找回密码", false, []string{}},
	{"password.question.verify", "全局", "提交提示问题验证", "POST", "/meol/findPasswdQuestionAccount.do", "提交提示问题验证", true, []string{"username", "questionId", "questionVal", "questionId2", "questionVal2", "questionId3", "questionVal3", "imgcode"}},
	{"password.question.reset", "全局", "打开密码重置页", "GET", "/meol/findPasswdQuestionPreReset.do", "打开密码重置页", false, []string{"code"}},
	{"password.captcha", "全局", "获取找回密码验证码", "GET", "/meol/getCaptcha.do", "获取找回密码验证码", false, []string{}},
	{"personal.profile.update", "个人", "提交个人资料", "POST", "/meol/popups/student_info_modify_do.jsp", "提交个人资料", true, []string{"SID", "from", "rd", "IPT_EMAIL", "IPT_PHONE", "description"}},
	{"personal.password.update", "个人", "修改密码", "POST", "/meol/popups/password_do.jsp", "修改密码", true, []string{"uid", "oldpass", "newpass", "rnewpass"}},
	{"personal.security-question.open", "个人", "设置安全问题", "GET", "/meol/validateQuestion.do", "设置安全问题", false, []string{}},
	{"personal.security-question.update", "个人", "提交安全问题", "POST", "/meol/validateQuestionDo.do", "提交安全问题", true, []string{"secret", "questionId", "questionVal", "questionId2", "questionVal2", "questionId3", "questionVal3"}},
	{"personal.email.verify", "个人", "发送邮箱验证", "GET", "/meol/validateEmailSend.do", "发送邮箱验证", true, []string{}},
	{"personal.mobile.send-sms", "个人", "发送绑定手机验证码", "POST", "/meol/sendSms.do", "发送绑定手机验证码", true, []string{"mobile", "opertionType"}},
	{"personal.mobile.login-send-sms", "个人", "发送手机登录验证码", "POST", "/meol/sendSms.do", "发送手机登录验证码", true, []string{"mobile", "opertionType=loginoperation"}},
	{"personal.mobile.bind", "个人", "绑定手机", "POST", "/meol/bindMobileDo.do", "绑定手机", true, []string{"mobile", "randomcode"}},
	{"personal.mobile.login", "个人", "手机验证码登录", "POST", "/meol/mobileLogin.do", "手机验证码登录", true, []string{"mobile", "randomcode"}},
	{"personal.mobile.ignore", "个人", "暂不绑定手机", "GET", "/meol/bindMobileIgnore.do", "暂不绑定手机", true, []string{}},
	{"personal.notifications.sort", "个人", "通知排序/分页", "GET", "/meol/common/inform/index_stu.jsp", "通知排序/分页", false, []string{"s_order", "s_page", "s_gotopage"}},
	{"global.notifications.all", "全局", "查看全部通知", "GET", "/meol/homepage/common/inform_all.jsp", "查看全部通知", false, []string{"s_page", "s_gotopage"}},
	{"global.course.search", "全局", "课程名称/编号查询", "POST", "/meol/course.do", "课程名称/编号查询", false, []string{"deptId", "s_keywordrealation", "s_keyword"}},
	{"department.teachers", "虚拟教研室", "教研室教师", "GET", "/meol/teacher.do", "教研室教师", false, []string{"deptId", "pagingPage", "pagingNumberPer"}},
	{"honor.courses", "虚拟教研室", "荣誉课程", "GET", "/meol/honLesson.do", "荣誉课程", false, []string{"cpiCode", "cpId"}},
	{"honor.teachers", "虚拟教研室", "荣誉教师", "GET", "/meol/honTeacher.do", "荣誉教师", false, []string{"cpi", "cpicode"}},
	{"activity.search", "活动", "研究型教学查询", "POST", "/meol/activity.do?menuId=3", "研究型教学查询", false, []string{"radio", "issuename"}},
	{"activity.course-list", "活动", "研究型教学课程列表", "GET", "/meol/homepage/V8/include/issue_course_list.jsp", "研究型教学课程列表", false, []string{"radiovalue", "issuename"}},
	{"platform.login", "全局", "旧版平台登录", "POST", "/meol/loginCheck.do", "旧版平台登录", true, []string{"logintoken", "IPT_LOGINUSERNAME", "IPT_LOGINPASSWORD"}},
	{"research.course.search", "研究型教学", "筛选课程研究型教学", "POST", "/meol/issueteach/issue/courseissue_list_stu.jsp", "筛选课程研究型教学", false, []string{"selectcourse"}},
	{"research.my.search", "研究型教学", "筛选我的研究型教学", "POST", "/meol/issueteach/issue/myissue/my_issue_allcourse.jsp", "筛选我的研究型教学", false, []string{"selectcourse"}},
	{"excellent.apply.sort", "精品课", "排序当前申报", "GET", "/meol/jpk/teacher/ela_sect_apply.jsp", "排序当前申报", false, []string{"sortColumn", "sortDirection", "open", "pagingPage", "pagingNumberPer"}},
	{"excellent.course.sort", "精品课", "排序历年精品课", "GET", "/meol/jpk/teacher/ela_sect.jsp", "排序历年精品课", false, []string{"sortColumn", "sortDirection", "pagingPage", "pagingNumberPer"}},
	{"excellent.course.search", "精品课", "筛选申报课程", "POST", "/meol/jpk/teacher/coursemanage_byselect.jsp", "筛选申报课程", false, []string{"sessionId", "courseName", "instructorName", "diciplineId", "departmentId"}},
	{"excellent.course.open", "精品课", "浏览申报课程", "GET", "/meol/jpk/course/index.jsp", "浏览申报课程", false, []string{"courseId"}},
	{"social.friend.search", "学习社区", "找人", "POST", "/meol/social/friendSearch.do", "找人", false, []string{"nickName", "gender", "school", "entranceYear", "className", "speciality", "pagingPage", "pagingNumberPer"}},
	{"social.friend.page", "学习社区", "找人分页", "GET", "/meol/social/friendSearch.do", "找人分页", false, []string{"sortColumn", "sortDirection", "nickName", "pagingPage", "pagingNumberPer"}},
	{"social.course.search", "学习社区", "找课程", "GET", "/meol/social/coursesSearch.do", "找课程", false, []string{"attentionType", "keyword", "pagingPage", "pagingNumberPer"}},
	{"social.course.search-submit", "学习社区", "筛选课程", "POST", "/meol/social/coursesSearch.do", "筛选课程", false, []string{"attentionType", "name", "numb", "teacherName", "pagingPage", "pagingNumberPer"}},
	{"social.circle.search", "学习社区", "找圈子", "GET", "/meol/social/studyCircleSearch.do", "找圈子", false, []string{"keyword", "pagingPage", "pagingNumberPer"}},
	{"social.circle.search-submit", "学习社区", "筛选圈子", "POST", "/meol/social/studyCircleSearch.do", "筛选圈子", false, []string{"title", "creator", "pagingPage", "pagingNumberPer"}},
	{"social.circle.open", "学习社区", "打开学习圈", "GET", "/meol/social/studyCircleInfo.do", "打开学习圈", false, []string{"studyCircleId"}},
	{"social.circle.list", "学习社区", "我的学习圈", "GET", "/meol/social/studyCircleList.do", "我的学习圈", false, []string{"userId", "genre", "pagingPage", "pagingNumberPer"}},
	{"social.person.open", "学习社区", "打开社区个人主页", "GET", "/meol/social/viewPersonInfo.do", "打开社区个人主页", false, []string{"userId", "genre"}},
	{"social.news.list", "学习社区", "读取社区动态", "GET", "/meol/social/listNews.do", "读取社区动态", false, []string{"userId", "genre", "type"}},
	{"social.news.more", "学习社区", "加载更多社区动态", "POST", "/meol/social/listNewsMore.do", "加载更多社区动态", false, []string{"logTime", "type", "userId"}},
	{"social.topics.list", "学习社区", "读取个人话题", "GET", "/meol/social/listTopics.do", "读取个人话题", false, []string{"userId", "genre", "pagingPage", "pagingNumberPer"}},
	{"social.attention.list", "学习社区", "读取关注列表", "GET", "/meol/social/listAttention.do", "读取关注列表", false, []string{"userId", "genre", "type"}},
	{"social.attention.more", "学习社区", "加载更多关注", "POST", "/meol/social/listAttentionMore.do", "加载更多关注", false, []string{"logTime", "type", "userId"}},
	{"social.fans.list", "学习社区", "读取粉丝列表", "GET", "/meol/social/listMyFans.do", "读取粉丝列表", false, []string{"userId", "genre", "pagingPage", "pagingNumberPer"}},
	{"social.message.add", "学习社区", "发布社区动态", "POST", "/meol/social/addMessage.do", "发布社区动态", true, []string{"type", "studyCircleId", "saytext", "imgId"}},
	{"social.topic.reply", "学习社区", "评论/回复话题", "POST", "/meol/social/addTopicReply.do", "评论/回复话题", true, []string{"topicId", "topicReplyId", "content"}},
	{"social.attention.add", "学习社区", "添加关注", "POST", "/meol/social/addAttention.do", "添加关注", true, []string{"objId", "type"}},
	{"social.attention.delete", "学习社区", "取消关注", "POST", "/meol/social/deleteAttention.do", "取消关注", true, []string{"objId", "type", "attentionId"}},
	{"social.circle.join", "学习社区", "加入学习圈", "POST", "/meol/social/addCircleUser.do", "加入学习圈", true, []string{"userId", "studyCircleId"}},
	{"social.circle.exit", "学习社区", "退出学习圈", "POST", "/meol/social/circleUserExit.do", "退出学习圈", true, []string{"userId", "studyCircleId", "circleUserId"}},
	{"social.circle.create", "学习社区", "创建学习圈", "POST", "/meol/social/addStudyCircle.do", "创建学习圈", true, []string{"id", "genre", "creatorId", "from", "title", "content", "photoFile"}},
	{"social.person.edit", "学习社区", "编辑社区资料", "GET", "/meol/social/preUpdPersonInfo.do", "编辑社区资料", false, []string{}},
	{"social.person.update", "学习社区", "更新社区资料", "POST", "/meol/social/updPersonInfo.do", "更新社区资料", true, []string{"ticket", "id", "nickName", "gender", "birthday", "mobile", "email", "school", "entranceYear", "className", "speciality", "unit", "provice", "city", "briefIntro"}},
	{"social.circle.delete", "学习社区", "删除学习圈", "POST", "/meol/social/deleteStudyCircle.do", "删除学习圈", true, []string{"id", "genre", "userId"}},
	{"social.topic.delete", "学习社区", "删除话题", "POST", "/meol/social/deleteMessage.do", "删除话题", true, []string{"topicId"}},
	{"social.topic.reply-delete", "学习社区", "删除话题回复", "POST", "/meol/social/deleteTopicReply.do", "删除话题回复", true, []string{"id"}},
	{"social.news-topic.delete", "学习社区", "删除动态和话题", "POST", "/meol/social/deleteNewsAndTopic.do", "删除动态和话题", true, []string{"topicId", "newsId"}},
	{"social.fan.delete", "学习社区", "删除粉丝", "POST", "/meol/social/deleteMyFans.do", "删除粉丝", true, []string{"userId"}},
	{"social.photo.upload", "学习社区", "上传社区图片", "POST", "/meol/social/newUploadPhotos.do", "上传社区图片", true, []string{"file"}},
	{"social.photo.upload-temp", "学习社区", "上传社区图片临时文件", "POST", "/meol/social/uploadImg.do", "上传社区图片临时文件", true, []string{"file", "uid", "a"}},
	{"social.photo.delete-temp", "学习社区", "删除社区图片临时文件", "POST", "/meol/social/deleteImg.do", "删除社区图片临时文件", true, []string{"fileId"}},
	{"social.file.download", "学习社区", "下载社区文件", "GET", "/meol/downloadTheolFile.do", "下载社区文件", false, []string{"id"}},
	{"course.community.open", "学习社区", "进入社区课程", "GET", "/meol/lesson/mainJumpPage.jsp", "进入社区课程", false, []string{"courseId"}},
	{"personal.calendar.month", "个人", "按月日历", "GET", "/meol/common/calendar/month.jsp", "按月日历", false, []string{"date"}},
	{"personal.calendar.date", "个人", "按日日历", "GET", "/meol/common/calendar/date.jsp", "按日日历", false, []string{"date"}},
	{"course.apply.search", "学习管理", "检索可申请课程", "GET", "/meol/lesson/applynewcourse_stu.jsp", "检索可申请课程", false, []string{"CATID", "SEL_LESSON_CAT", "s_keyword", "s_keywordrealation", "button"}},
	{"course.apply.sort", "学习管理", "排序可申请课程", "GET", "/meol/lesson/applynewcourse_stu.jsp", "排序可申请课程", false, []string{"s_order", "CATID"}},
	{"course.apply.summary", "学习管理", "查看课程简介", "GET", "/meol/lesson/coursesum.jsp", "查看课程简介", false, []string{"lid", "fancybox"}},
	{"course.apply.join", "学习管理", "申请加入课程", "GET", "/meol/lesson/applyjoincourse.jsp", "申请加入课程", true, []string{"lid"}},
	{"course.archive.open", "学习管理", "查看历史课程", "GET", "/meol/archive/archiveCourseListByStu.do", "查看历史课程", false, []string{}},
	{"mail.message.action", "站内邮箱", "删除/标记/移动邮件", "POST", "/meol/common/mail/inputbox.jsp", "删除/标记/移动邮件", true, []string{"_action", "allbox"}},
	{"mail.message.delete", "站内邮箱", "删除邮件", "POST", "/meol/common/mail/inputbox.jsp", "删除邮件", true, []string{"_action", "allbox", "ids"}},
	{"mail.message.mark-unread", "站内邮箱", "标记未读", "POST", "/meol/common/mail/inputbox.jsp", "标记未读", true, []string{"_action", "allbox", "ids"}},
	{"mail.message.move", "站内邮箱", "移动邮件", "POST", "/meol/common/mail/inputbox.jsp", "移动邮件", true, []string{"_action", "allbox", "ids"}},
	{"mail.search", "站内邮箱", "搜索邮件", "POST", "/meol/common/mail/search.jsp", "搜索邮件", false, []string{"_action", "search", "InFolder", "Search", "allbox"}},
	{"mail.trash.empty", "站内邮箱", "清空垃圾箱", "GET", "/meol/common/mail/garbage.jsp?action=empty", "清空垃圾箱", true, []string{}},
	{"mail.folder.action", "站内邮箱", "邮箱文件夹操作", "POST", "/meol/common/mail/managefolder.jsp", "邮箱文件夹操作", true, []string{"_action", "_HMaction", "allbox"}},
	{"mail.folder.delete", "站内邮箱", "删除邮箱文件夹", "POST", "/meol/common/mail/managefolder.jsp", "删除邮箱文件夹", true, []string{"_action", "_HMaction", "allbox"}},
	{"mail.folder.empty", "站内邮箱", "清空邮箱文件夹", "GET", "/meol/common/mail/managefolder.jsp?action=_empty", "清空邮箱文件夹", true, []string{}},
	{"mail.contact.action", "站内邮箱", "联系人操作", "POST", "/meol/common/mail/managecontact.jsp", "联系人操作", true, []string{"_action", "allbox"}},
	{"mail.contact.delete", "站内邮箱", "删除联系人", "POST", "/meol/common/mail/managecontact.jsp", "删除联系人", true, []string{"_action", "allbox", "ids"}},
	{"mail.trash.delete-forever", "站内邮箱", "永久删除邮件", "POST", "/meol/common/mail/garbage.jsp", "永久删除邮件", true, []string{"_action", "allbox", "ids"}},
	{"mail.send", "站内邮箱", "发送邮件", "POST", "/meol/common/mail/composemail.jsp", "发送邮件", true, []string{"operation", "importance", "action", "from", "fID", "to", "subject", "sentbox"}},
	{"mail.save", "站内邮箱", "保存邮件草稿", "POST", "/meol/common/mail/composemail.jsp", "保存邮件草稿", true, []string{"operation", "importance", "action", "from", "fID", "to", "subject", "sentbox"}},
	{"mail.folder.save", "站内邮箱", "保存邮箱文件夹", "POST", "/meol/common/mail/editfolder.jsp", "保存邮箱文件夹", true, []string{"action", "folderID", "foldername", "from"}},
	{"mail.contact.save", "站内邮箱", "保存邮箱联系人", "POST", "/meol/common/mail/editcontact.jsp", "保存邮箱联系人", true, []string{"operation", "contactID", "addanother", "from", "contactUsername", "name", "email", "vip", "department", "houseAddress", "telephone", "mobile", "note"}},
	{"mail.settings.save", "站内邮箱", "保存邮箱设置", "POST", "/meol/common/mail/mailsetting.jsp", "保存邮箱设置", true, []string{"_action", "inforWay", "saveProp"}},
	{"mail.message.open", "站内邮箱", "查看邮件详情", "GET", "/meol/common/mail/mail.jsp", "查看邮件详情", false, []string{"id"}},
	{"mail.contact.search", "站内邮箱", "搜索联系人", "GET", "/meol/common/mail/search_info.jsp", "搜索联系人", false, []string{"contactUsername"}},
	{"courses.search", "个人", "课程搜索", "POST", "/meol/lesson/blen.student.lesson.list.jsp", "课程搜索", false, []string{"name", "tutorName"}},
	{"courses.move-up", "个人", "课程上移", "GET", "/meol/lesson/blen.student.lesson.list.jsp", "课程上移", true, []string{"ACTION", "lid"}},
	{"courses.move-down", "个人", "课程下移", "GET", "/meol/lesson/blen.student.lesson.list.jsp", "课程下移", true, []string{"ACTION", "lid"}},
	{"course.open", "课程", "打开课程", "GET", "/meol/jpk/course/layout/newpage/index.jsp", "打开课程", false, []string{"courseId"}},
	{"course.public.open", "课程", "打开公开课程", "GET", "/meol/homepage/course/course_index.jsp", "打开公开课程", false, []string{"courseId"}},
	{"course.lesson-home.open", "课程", "打开课程学习首页", "GET", "/meol/jpk/course/layout/lesson/index.jsp", "打开课程学习首页", false, []string{"courseId"}},
	{"course.default.open", "课程", "打开课程介绍首页", "GET", "/meol/jpk/course/layout/newpage/default_demonstrate.jsp", "打开课程介绍首页", false, []string{"courseId"}},
	{"course.unit-blank.open", "课程", "打开单元学习容器", "GET", "/meol/jpk/course/layout/_blank.jsp", "打开单元学习容器", false, []string{}},
	{"course.qrcode.open", "课程", "查看课程二维码", "GET", "/meol/lesson/qrcode.jsp", "查看课程二维码", false, []string{"lessonId"}},
	{"course.stat", "课程", "读取课程统计", "POST", "/meol/jpk/course/userLessonStat.jsp", "读取课程统计", false, []string{"courseId"}},
	{"course.online-heartbeat", "课程", "记录在线时长", "POST", "/meol/lesson/onlinetime_listener.jsp", "记录在线时长", true, []string{"lessId"}},
	{"online-help.open", "公共组件", "打开在线帮助", "GET", "/meol/common/help/help.jsp", "打开在线帮助", false, []string{"qstr"}},
	{"course.mailbox.open", "课程", "打开站内邮箱", "GET", "/meol/common/mail/inputbox.jsp", "打开站内邮箱", false, []string{}},
	{"course.note.compose", "课程", "写课程笔记", "GET", "/meol/common/notebook/course_write_note.jsp", "写课程笔记", false, []string{"uid", "lid"}},
	{"course.note.book", "课程", "查看课程笔记本", "GET", "/meol/common/notebook/course_notebook.jsp", "查看课程笔记本", false, []string{"tag", "lid"}},
	{"course.forum.frame", "课程", "打开讨论区弹窗", "GET", "/meol/common/faq/forum.jsp", "打开讨论区弹窗", false, []string{"lid"}},
	{"course.livevod.open", "课程", "打开直播预约", "GET", "/meol/livevod/liveVodAppointmentStuList.do", "打开直播预约", false, []string{"courseId"}},
	{"course.ccvod.open", "课程", "打开 CC 直播频道", "GET", "/meol/ccvod/ccVodChannelStuList.do", "打开 CC 直播频道", false, []string{"courseId"}},
	{"course.netmeeting.open", "课程", "打开网络会议", "GET", "/meol/netmeeting/netMeetingPreAddUser.do", "打开网络会议", false, []string{"courseId"}},
	{"course.tencent-meeting.open", "课程", "打开腾讯会议", "GET", "/meol/tencentmeeting/tenCentMeetingPreAddUser.do", "打开腾讯会议", false, []string{"courseId", "meetingStatus"}},
	{"podcast.search", "播客", "播客筛选查询", "POST", "/meol/custom.do?menuId=4", "播客筛选查询", false, []string{"title", "typeid", "pagingNumberPer"}},
	{"podcast.play", "播客", "播放播客", "GET", "/meol/common/stream/player.jsp", "播放播客", false, []string{"fileId", "vId"}},
	{"podcast.recommend", "播客", "推荐播客", "GET", "/meol/common/vblog/recommend.jsp", "推荐播客", true, []string{"id"}},
	{"podcast.favorite", "播客", "收藏播客", "GET", "/meol/common/vblog/favorite/add_favorite.jsp", "收藏播客", true, []string{"id"}},
	{"podcast.list.search", "播客", "筛选全校视频", "GET", "/meol/common/vblog/listvideo.jsp", "筛选全校视频", false, []string{"title", "typeid"}},
	{"podcast.list.sort", "播客", "排序全校视频", "GET", "/meol/common/vblog/listvideo.jsp", "排序全校视频", false, []string{"sortColumn", "sortDirection", "pagingPage", "pagingNumberPer"}},
	{"podcast.favorite.delete", "播客", "删除播客收藏", "POST", "/meol/common/vblog/favorite/del_favorite.jsp", "删除播客收藏", true, []string{"ids"}},
	{"course.column.open", "课程", "打开课程栏目", "GET", "/meol/jpk/course/course_column_preview_transfer.jsp?tagbug=client", "打开课程栏目", false, []string{"columnId"}},
	{"course.notice.list", "课程", "课程通知列表", "GET", "/meol/article/ListNews.do", "课程通知列表", false, []string{"courseId", "s_order", "s_page"}},
	{"course.notice.detail", "课程", "课程通知详情", "GET", "/meol/jpk/course/layout/course_meswrap.jsp", "课程通知详情", false, []string{"nid", "courseId"}},
	{"course.resource.search", "课程", "课程资源查询", "GET", "/meol/common/script/search.jsp", "课程资源查询", false, []string{"folderid", "lid", "groupid", "keyword", "resourceType", "chapter", "knowledge"}},
	{"course.resource.open-folder", "课程", "进入资源文件夹", "GET", "/meol/common/script/listview.jsp", "进入资源文件夹", false, []string{"acttype", "folderid", "lid"}},
	{"course.resource.preview", "课程", "预览/下载课程资源", "GET", "/meol/common/script/preview/download_preview.jsp", "预览/下载课程资源", false, []string{"fileid", "resid", "lid"}},
	{"course.analytics", "课程", "学习分析", "GET", "/meol/jpk/course/blended_module/mod_la_stu.jsp", "学习分析", false, []string{"lid"}},
	{"course.score", "课程", "课程成绩", "GET", "/meol/newscoremanagement/scoreView.do", "课程成绩", false, []string{"lid"}},
	{"course.learning-record", "课程", "课程学习记录", "GET", "/meol/common/newscoremanagement/stu_course_detail.jsp", "课程学习记录", false, []string{"lid", "uid"}},
	{"course.notes.search", "课程", "学习笔记查询", "POST", "/meol/common/notebook/column_notebook_share.jsp", "学习笔记查询", false, []string{"lid", "tag", "s_keyword", "userId", "listLimit"}},
	{"course.faq.search", "课程", "FAQ 查询", "GET", "/meol/common/faq/course_tea_faq.jsp", "FAQ 查询", false, []string{"lid", "kid", "s_keyword", "isRecommend"}},
	{"course.forum.discuss", "课程", "打开讨论区版面", "GET", "/meol/common/faq/tea_discuss.jsp", "打开讨论区版面", false, []string{"forumid"}},
	{"course.faq.report", "课程", "提交问题反馈", "POST", "/meol/popups/bugreport_do.jsp", "提交问题反馈", true, []string{"BUG_SUBJECT", "BUG_HTMLFORMAT", "BUG_CONTENT", "BUG_EMAIL"}},
	{"course.forum.search", "课程", "讨论区搜索", "POST", "/meol/common/faq/forum_search.jsp", "讨论区搜索", false, []string{"forumid", "s_keyword", "username"}},
	{"course.forum.post", "课程", "发表话题/回复", "POST", "/meol/common/faq/postArticle.jsp?opt=topost", "发表话题/回复", true, []string{"forumid", "threadid", "parentid", "subject", "content"}},
	{"system.faq.search", "公共组件", "搜索系统帮助", "POST", "/meol/common/faq/sys_faq.jsp", "搜索系统帮助", false, []string{"lid", "kid", "s_keyword", "s_keywordrealation", "search", "s_gotopage"}},
	{"course.survey.list", "课程", "课程问卷列表", "POST", "/meol/common/questionaire/stu_survey.jsp", "课程问卷列表", false, []string{"lid", "moduleType", "s_order", "s_page"}},
	{"course.survey.take", "课程", "参加问卷", "GET", "/meol/common/questionaire/survey.jsp", "参加问卷", false, []string{"paperId", "lid", "moduleType"}},
	{"course.survey.result", "课程", "查看问卷结果", "GET", "/meol/common/questionaire/survey_result.jsp", "查看问卷结果", false, []string{"paperid", "moduleType"}},
	{"course.question.search", "课程", "题库查询", "POST", "/meol/common/question/questionbank/student/list.jsp", "题库查询", false, []string{"cateId", "questionType", "chapterId", "sectionId", "knowledgeKey", "keywords", "pagingNumberPer"}},
	{"course.paper.search", "课程", "试卷库查询", "GET", "/meol/common/question/paperbank/student/list.jsp", "试卷库查询", false, []string{"cateId", "keywords", "pagingNumberPer"}},
	{"course.test.list", "课程", "在线测试列表", "GET", "/meol/common/question/test/student/list.jsp", "在线测试列表", false, []string{"cateId", "pagingNumberPer", "pagingPage"}},
	{"course.test.open", "课程", "打开在线测试", "GET", "/meol/common/question/test/student/stu_qtest_navigate.jsp", "打开在线测试", false, []string{"testId"}},
	{"course.micro-lessons", "课程", "教学播课", "GET", "/meol/microlessonunit/viewMicroLesson.do", "教学播课", false, []string{"courseId", "ustatus"}},
	{"resource.search", "资源中心", "资源检索", "GET", "/moocresource/search/browser.jsp", "资源检索", false, []string{"id", "keyword"}},
	{"resource.home.search", "资源中心", "资源首页搜索", "POST", "/moocresource/view/reslist.jsp", "资源首页搜索", false, []string{"inputkeyword", "domain"}},
	{"resource.bank.subject", "资源中心", "资源库分类浏览", "GET", "/moocresource/banks/search/bank_index.jsp", "资源库分类浏览", false, []string{"bankId", "viewtype", "subjectId", "resourceType", "mediaType", "pagingPage", "pagingNumberPer"}},
	{"resource.bank.open", "资源中心", "打开资源库", "GET", "/moocresource/banks/search/bank.jsp", "打开资源库", false, []string{"bankId"}},
	{"resource.bank.list", "资源中心", "查询专题库资源", "POST", "/moocresource/banks/search/reslist.jsp", "查询专题库资源", false, []string{"bankId", "subjectid", "courseName", "keyWord", "courseType", "mediaType", "courseLevel", "pagingPage", "pagingNumberPer"}},
	{"resource.bank.keyword", "资源中心", "关键词查询资源", "POST", "/moocresource/courses/searchres.jsp", "关键词查询资源", false, []string{"keyword"}},
	{"resource.excellent.search", "资源中心", "精品课程搜索", "POST", "/moocresource/courses/excellent/course_list_query.jsp", "精品课程搜索", false, []string{"inputkeyword", "universityId", "domain"}},
	{"resource.open.search", "资源中心", "全球开放课程搜索", "POST", "/moocresource/courses/ocw/ocwcoursesearch.jsp", "全球开放课程搜索", false, []string{"inputkeyword", "universityId", "domain"}},
	{"resource.video.search", "资源中心", "公开视频搜索", "POST", "/moocresource/courses/xiaoyouhui/video_list_query.jsp", "公开视频搜索", false, []string{"inputkeyword", "bankType", "domain"}},
	{"resource.mooc.search", "资源中心", "MOOC搜索", "POST", "/moocresource/courses/xiaoyouhui/mooc_list_query.jsp", "MOOC搜索", false, []string{"inputkeyword", "bankType", "domain"}},
	{"resource.micro.search", "资源中心", "微课程搜索", "POST", "/moocresource/courses/xiaoyouhui/micro_list_query.jsp", "微课程搜索", false, []string{"inputkeyword", "bankType", "domain"}},
	{"resource.tag.search", "资源中心", "标签资源搜索", "GET", "/moocresource/courses/xiaoyouhui/searchresourcebytag.jsp", "标签资源搜索", false, []string{"tagName"}},
	{"resource.entry.open", "资源中心", "打开外部资源条目", "GET", "/moocresource/search/browser_by_entry.jsp", "打开外部资源条目", false, []string{"entry"}},
	{"resource.bank.login", "资源中心", "打开资源库登录提示", "GET", "/moocresource/banks/login.jsp", "打开资源库登录提示", false, []string{"url"}},
	{"resource.sso.open", "资源中心", "进入资源中心 SSO", "POST", "/moocresource/eol_sso_new.jsp", "进入资源中心 SSO", true, []string{"user", "time", "verify", "columnId", "moduleType", "shareResId", "bankId", "sso", "resourceIndex"}},
	{"resource.attribute", "资源中心", "资源属性", "GET", "/moocresource/banks/search/attribute.jsp", "资源属性", false, []string{"erid"}},
	{"resource.related", "资源中心", "相关资源", "GET", "/moocresource/banks/relateres.jsp", "相关资源", false, []string{"resId"}},
	{"resource.my-list", "资源中心", "我的资源", "GET", "/moocresource/myres/resourceInfoList.do", "我的资源", false, []string{"resourceName", "keyword", "resourceType", "directory"}},
	{"resource.list.search", "资源中心", "筛选我的资源", "POST", "/moocresource/resource/resourceInfoList.do", "筛选我的资源", false, []string{"title", "keyWord", "type", "mySelfFolderId"}},
	{"resource.list.page", "资源中心", "我的资源分页", "POST", "/moocresource/resource/resourceInfoList.do", "我的资源分页", false, []string{"folderId", "oldFolderId", "pagingNumberPer", "pagingPage"}},
	{"resource.add", "资源中心", "添加资源", "GET", "/moocresource/resource/preAddResourceInfo.do", "添加资源", false, []string{"mySelfFolderId", "oldFolderId"}},
	{"resource.move-batch", "资源中心", "批量移动资源", "POST", "/moocresource/resource/moveResourceInfoByBatch.do", "批量移动资源", true, []string{"beanIds", "oldFolderId"}},
	{"resource.delete-batch", "资源中心", "批量删除资源", "POST", "/moocresource/resource/deleteResourceInfoByBatch.do", "批量删除资源", true, []string{"beanIds", "oldFolderId"}},
	{"resource.my-folders", "资源中心", "我的资源文件夹", "GET", "/moocresource/myres/listMyFolder.do", "我的资源文件夹", false, []string{"folderName"}},
	{"resource.my-folders-frame", "资源中心", "读取资源目录", "GET", "/moocresource/resource/listMyFolder.do", "读取资源目录", false, []string{"folderName", "pagingPage", "pagingNumberPer"}},
	{"resource.favorites", "资源中心", "资源收藏", "GET", "/moocresource/myres/favorite_detail.jsp", "资源收藏", false, []string{"folderId", "resourceName"}},
	{"resource.favorites-frame", "资源中心", "读取收藏资源", "GET", "/moocresource/myres/favorite/favorite_detail.jsp", "读取收藏资源", false, []string{"folderId", "resourceName"}},
	{"resource.follows", "资源中心", "资源关注", "GET", "/moocresource/myres/attentionres_list.jsp", "资源关注", false, []string{}},
	{"resource.follows-frame", "资源中心", "读取关注资源", "GET", "/moocresource/myres/attentionres/attentionres_list.jsp", "读取关注资源", false, []string{}},
	{"resource.comments", "资源中心", "资源评论", "GET", "/moocresource/myres/reviewlist.jsp", "资源评论", false, []string{}},
	{"resource.comments-frame", "资源中心", "读取资源评论", "GET", "/moocresource/myres/myreview/reviewlist.jsp", "读取资源评论", false, []string{}},
	{"resource.shares", "资源中心", "共享资源", "GET", "/moocresource/myres/listShareRes.do", "共享资源", false, []string{"resourceName", "sharer", "keyword", "pagingPage"}},
	{"resource.shares-frame", "资源中心", "读取共享资源", "GET", "/moocresource/resource/listShareRes.do", "读取共享资源", false, []string{"resourceName", "sharer", "keyword", "pagingPage"}},
	{"resource.personal-info", "资源中心", "资源个人统计", "GET", "/moocresource/myres/class_personal_info.jsp", "资源个人统计", false, []string{}},
	{"resource.personal-info-frame", "资源中心", "读取资源个人统计", "GET", "/moocresource/personalset/class_personal_info.jsp", "读取资源个人统计", false, []string{}},
	{"resource.view", "资源中心", "查看共享资源详情", "GET", "/moocresource/resource/viewResourceInfo.do", "查看共享资源详情", false, []string{"id"}},
	{"resource.favorite", "资源中心", "收藏/取消收藏资源", "POST", "/moocresource/myres/favorite/favorite.jsp", "收藏/取消收藏资源", true, []string{"resId"}},
	{"resource.rate", "资源中心", "资源评分", "POST", "/moocresource/search/res_evaluate.jsp", "资源评分", true, []string{"score", "resId"}},
	{"resource.download", "资源中心", "下载资源", "GET", "/moocresource/servlet/ResourceDownload", "下载资源", false, []string{"erid"}},
	{"resource.tag-exists", "资源中心", "检查资源标签", "POST", "/moocresource/taglibrary/tagExist.do", "检查资源标签", false, []string{"tagName", "objId", "objType"}},
	{"resource.tag-add", "资源中心", "添加资源标签", "POST", "/moocresource/taglibrary/tagAdd.do", "添加资源标签", true, []string{"tagName", "objId", "objType"}},
	{"folder.add", "资源中心", "添加资源目录", "GET", "/moocresource/resource/preAddFolder.do", "添加资源目录", false, []string{"fid"}},
	{"folder.update", "资源中心", "更新资源目录", "POST", "/moocresource/resource/updateMySelfFolder.do", "更新资源目录", true, []string{"id", "level", "title"}},
	{"folder.share-batch", "资源中心", "共享/取消共享目录", "POST", "/moocresource/resource/shareFolderBatch.do", "共享/取消共享目录", true, []string{"folderIds", "shareType"}},
	{"folder.list", "资源中心", "管理收藏夹目录", "GET", "/moocresource/resource/myfolder_list.jsp", "管理收藏夹目录", false, []string{"indexStatus"}},
	{"follow.add", "资源中心", "添加资源关注", "GET", "/moocresource/myres/attentionres/attentionres_add.jsp", "添加资源关注", false, []string{}},
	{"homework.list", "作业", "作业列表", "GET", "/meol/hw/stu/hwStuHwtList.do", "作业列表", false, []string{"courseId", "title", "pagingNumberPer", "um", "pagingPage", "sortColumn", "sortDirection"}},
	{"homework.submit", "作业", "提交作业", "POST", "/meol/hw/stu/hwStuSubmitDo.do", "提交作业", true, []string{"hwaId", "courseId", "um", "hwtId", "answer"}},
	{"homework.reviews", "作业", "互评任务", "GET", "/meol/hw/stu/hwReviewList.do", "互评任务", false, []string{"hwtId", "courseId", "um"}},
	{"homework.review.save", "作业", "保存互评", "POST", "/meol/hw/stu/hwStuReviewSave.do", "保存互评", true, []string{"hwtId", "mutualId", "um"}},
	{"homework.score", "作业", "作业成绩", "GET", "/meol/hw/stu/hwShowScore.do", "作业成绩", false, []string{"hwtId", "um"}},
	{"homework.result", "作业", "互评结果", "GET", "/meol/hw/stu/hwMutualList.do", "互评结果", false, []string{"hwtId", "um"}},
	{"homework.complain", "作业", "作业评价申诉", "POST", "/meol/hw/stu/hwShowReviewDetails.do", "作业评价申诉", true, []string{"hwtId", "um", "type"}},
}

func teachingCatalog() map[string]any {
	routes := make([]map[string]any, 0, len(teachingRoutes))
	for _, item := range teachingRoutes {
		routes = append(routes, map[string]any{"name": item.name, "section": item.section, "label": item.label, "path": item.path, "method": item.method, "mutating": item.mutating, "description": item.description})
	}
	actions := make([]map[string]any, 0, len(teachingActions))
	for _, item := range teachingActions {
		actions = append(actions, map[string]any{"name": item.name, "section": item.section, "label": item.label, "path": item.path, "method": item.method, "mutating": item.mutating, "fields": item.fields})
	}
	apis := make([]map[string]any, 0, len(teachingAPIs))
	for _, item := range teachingAPIs {
		apis = append(apis, map[string]any{"name": item.name, "description": item.description, "path": item.path, "method": item.method, "mutating": item.mutating})
	}
	return map[string]any{"ok": true, "submitted": false, "confirmed": true, "evidence": "confirmed", "service": "网络教学平台", "routes": routes, "actions": actions, "apis": apis, "route_count": len(routes), "action_count": len(actions), "api_count": len(apis)}
}

func teachingLookup(name, method string, methodSet bool) (teachingCatalogItem, bool, bool) {
	needle := strings.ToLower(strings.TrimSpace(name))
	matches := make([]teachingCatalogItem, 0, 3)
	for _, list := range [][]teachingCatalogItem{teachingRoutes, teachingActions, teachingAPIs} {
		for _, item := range list {
			if strings.ToLower(item.name) == needle || strings.ToLower(item.label) == needle {
				matches = append(matches, item)
			}
		}
	}
	if len(matches) == 0 {
		return teachingCatalogItem{}, false, false
	}
	if methodSet {
		filtered := matches[:0]
		for _, item := range matches {
			if strings.EqualFold(item.method, method) {
				filtered = append(filtered, item)
			}
		}
		matches = filtered
		if len(matches) == 0 {
			return teachingCatalogItem{}, false, false
		}
	}
	paths := make(map[string]bool, len(matches))
	for _, item := range matches {
		paths[item.path] = true
	}
	if len(paths) > 1 {
		return matches[0], true, true
	}
	chosen := matches[0]
	if !methodSet {
		for _, item := range matches {
			if strings.EqualFold(item.method, "GET") {
				chosen = item
				break
			}
		}
	}
	for _, item := range matches {
		chosen.mutating = chosen.mutating || item.mutating
		for _, field := range item.fields {
			if !containsString(chosen.fields, field) {
				chosen.fields = append(chosen.fields, field)
			}
		}
	}
	return chosen, true, false
}
